# XPM images for the DRI configuration GUI

# The icons are downloaded from
# http://tigert.gimp.org/gnome/gnome-stock/ They are part of the gnome
# distribution and as such distrubuted under the GPL.

# The DRI logo comes from dri.sf.net. The palette was compressed to 91
# colors using the Gimp so that each pixel can be represented by one
# byte cutting the size in half.

tb_down_arrow_xpm = [
"25 24 42 1",
" 	c None",
".	c #000000",
"+	c #243221",
"@	c #C6D7C3",
"#	c #67925C",
"$	c #608C56",
"%	c #5B8851",
"&	c #36582E",
"*	c #FFFFFF",
"=	c #F3F7F3",
"-	c #F4F7F4",
";	c #EFF3EE",
">	c #87AC7D",
",	c #83AA7A",
"'	c #80A776",
")	c #6FA763",
"!	c #E4EBE2",
"~	c #F1F5F0",
"{	c #719A67",
"]	c #46703C",
"^	c #81A878",
"/	c #81A877",
"(	c #4E7C44",
"_	c #DFE8DD",
":	c #F2F6F1",
"<	c #EBF1EA",
"[	c #709864",
"}	c #49763F",
"|	c #84A979",
"1	c #DCE6D9",
"2	c #EEF3ED",
"3	c #DEE7DC",
"4	c #7DA473",
"5	c #739C6A",
"6	c #375930",
"7	c #D7E3D5",
"8	c #E9EFE8",
"9	c #729B68",
"0	c #516F4A",
"a	c #121B12",
"b	c #548149",
"c	c #B1C7AC",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"                         ",
"     ......+.......      ",
"     .@@@@@@###$%&.      ",
"      .*=-;;>,>').       ",
"      .!=~;;,>'{].       ",
"       .*;;;>^/(.        ",
"       ._:<<,'[}.        ",
"        .*<!/|(.         ",
"        .123456.         ",
"         .*7'(.          ",
"         .3890.          ",
"          a*b.           ",
"          .c6.           ",
"           ..            ",
"           ..            ",
"                         ",
"                         ",
"                         ",
"                         "]
tb_edit_xpm = [
"24 24 113 2",
"  	c None",
". 	c #000000",
"+ 	c #ADAD9C",
"@ 	c #959585",
"# 	c #DCDCC5",
"$ 	c #DFDFC8",
"% 	c #242424",
"& 	c #A7A796",
"* 	c #D7D7C1",
"= 	c #D9D9C3",
"- 	c #DCDCC4",
"; 	c #DDDDC7",
"> 	c #E1E1CA",
", 	c #D8BE6A",
"' 	c #A6A694",
") 	c #D6D6BF",
"! 	c #D8D8C2",
"~ 	c #DBDBC4",
"{ 	c #A2A291",
"] 	c #E3E3CB",
"^ 	c #B2B29F",
"/ 	c #8E7D45",
"( 	c #7C7C7C",
"_ 	c #646464",
": 	c #D5D5BD",
"< 	c #D5D5BF",
"[ 	c #D7D7C0",
"} 	c #9E9E8D",
"| 	c #ABAB98",
"1 	c #E1E1C9",
"2 	c #E5E5CD",
"3 	c #E9E9D1",
"4 	c #343434",
"5 	c #E7E7E7",
"6 	c #373736",
"7 	c #B8B8A6",
"8 	c #D3D3BC",
"9 	c #909081",
"0 	c #9F9F8E",
"a 	c #DDDDC5",
"b 	c #E0E0C8",
"c 	c #A2A292",
"d 	c #ECECD4",
"e 	c #EEEED5",
"f 	c #ECECEC",
"g 	c #EDEDED",
"h 	c #3D3D37",
"i 	c #8A8A7A",
"j 	c #E6E6CE",
"k 	c #9A9A8A",
"l 	c #EAEAD2",
"m 	c #EEEEE5",
"n 	c #3C3C3C",
"o 	c #8F8F80",
"p 	c #D0D0B9",
"q 	c #999988",
"r 	c #ECECD3",
"s 	c #EFEFD6",
"t 	c #EEEEE6",
"u 	c #505050",
"v 	c #929282",
"w 	c #D1D1B9",
"x 	c #969686",
"y 	c #E7E7CF",
"z 	c #EBEBD2",
"A 	c #F5F5DC",
"B 	c #D2D2BC",
"C 	c #E9E9D0",
"D 	c #EDEDD4",
"E 	c #E3E3DC",
"F 	c #797973",
"G 	c #D8D8C1",
"H 	c #919182",
"I 	c #949484",
"J 	c #EAEAD1",
"K 	c #D9D9CC",
"L 	c #BFBFB0",
"M 	c #ACACA5",
"N 	c #9F9F93",
"O 	c #98988F",
"P 	c #E4E4CC",
"Q 	c #AD8E30",
"R 	c #756020",
"S 	c #C4C4B0",
"T 	c #9D9D8D",
"U 	c #818174",
"V 	c #DFDFC7",
"W 	c #E2E2CA",
"X 	c #060605",
"Y 	c #9B9B8B",
"Z 	c #9C9C8C",
"` 	c #BEBEAE",
" .	c #8B8B7D",
"..	c #7E7E71",
"+.	c #C0C0AC",
"@.	c #C2C2AE",
"#.	c #C3C3AF",
"$.	c #DADAC3",
"%.	c #4E4E4E",
"&.	c #E8E8D0",
"*.	c #A0A090",
"=.	c #F2F2D9",
"-.	c #F3F3DA",
";.	c #F4F4DB",
">.	c #828274",
",.	c #EBEBD3",
"'.	c #F1F1D8",
").	c #F0F0D7",
"!.	c #A5A594",
"~.	c #BBBBA8",
"{.	c #CDCDB8",
"].	c #4D4D45",
"^.	c #A6A696",
"                                                ",
"                                                ",
"                          .                     ",
"                      . . + .                   ",
"                  . . @ # $ %             .     ",
"              . . & * = - ; > .         . , .   ",
"          . . ' ) * * ! ~ { ] ^ .     . , / .   ",
"        . ( _ ) : < [ } | 1 2 3 4   . , / .     ",
"        . 5 6 7 8 9 0 a b 2 c d e . , / .       ",
"        . f g h i < ~ b j k l e . , / .         ",
"        . m m n o p b q q r s . , / .           ",
"        . t u v w - x y z e . , / . A .         ",
"        . . x B ~ x ] C D . , / . A A E .       ",
"        . F G H I > y J . , / . A K L M N .     ",
"        . O ~ # $ P y Q R . . S T T T T U .     ",
"          . V b W 2 3 X . Y Z T T T T . .       ",
"          . ` 2 2 T  ...+.@.#.S A $..           ",
"            %.&.*.l D s =.-.;.=.>..             ",
"            . ,.d D s '.=.=.$..                 ",
"              . s ).'.=.3 !..                   ",
"              . ~.=.-.{.]..                     ",
"                . -.^..                         ",
"                  . .                           ",
"                                                "]
tb_exit_xpm = [
"24 24 13 1",
" 	c None",
".	c #000000",
"+	c #E4E4DC",
"@	c #BE7579",
"#	c #C67D81",
"$	c #2D2D2D",
"%	c #8A4D4F",
"&	c #9E575B",
"*	c #A75E5F",
"=	c #AF6668",
"-	c #B66D71",
";	c #CD8689",
">	c #080808",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"          .........     ",
"          .++++++..     ",
"          .++++++..     ",
"        ...++++++..     ",
"        .@.++++++..     ",
"   ......@#.++$.+..     ",
"   .%&*=-@#;.+.$+..     ",
"   .%&*=-@#;.++++..     ",
"   ......@#.+++++..     ",
"        .@.++++++..     ",
"        ...++++++..     ",
"          .++++....     ",
"          .++......     ",
"          ...>>>>>>     ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        "]
tb_new_xpm = [
"24 24 89 1",
" 	c None",
".	c #000000",
"+	c #ADAD9C",
"@	c #959585",
"#	c #DCDCC5",
"$	c #DFDFC8",
"%	c #242424",
"&	c #A7A796",
"*	c #D7D7C1",
"=	c #D9D9C3",
"-	c #DCDCC4",
";	c #DDDDC7",
">	c #E1E1CA",
",	c #A6A694",
"'	c #D6D6BF",
")	c #D8D8C2",
"!	c #DBDBC4",
"~	c #DFDFC7",
"{	c #E3E3CB",
"]	c #B2B29F",
"^	c #7C7C7C",
"/	c #646464",
"(	c #D5D5BD",
"_	c #D5D5BF",
":	c #D7D7C0",
"<	c #DADAC3",
"[	c #DEDEC6",
"}	c #E1E1C9",
"|	c #E5E5CD",
"1	c #E9E9D1",
"2	c #343434",
"3	c #E7E7E7",
"4	c #373736",
"5	c #B8B8A6",
"6	c #D3D3BC",
"7	c #D9D9C2",
"8	c #DDDDC5",
"9	c #E0E0C8",
"0	c #E8E8D0",
"a	c #ECECD4",
"b	c #EEEED5",
"c	c #ECECEC",
"d	c #EDEDED",
"e	c #3D3D37",
"f	c #CECEB7",
"g	c #E6E6CE",
"h	c #EAEAD2",
"i	c #F1F1D8",
"j	c #A5A594",
"k	c #EEEEE5",
"l	c #3C3C3C",
"m	c #8F8F80",
"n	c #D0D0B9",
"o	c #E4E4CB",
"p	c #EAEAD1",
"q	c #ECECD3",
"r	c #EFEFD6",
"s	c #F2F2D9",
"t	c #F3F3DA",
"u	c #EEEEE6",
"v	c #505050",
"w	c #929282",
"x	c #D1D1B9",
"y	c #E7E7CF",
"z	c #EBEBD2",
"A	c #F4F4DB",
"B	c #F5F5DC",
"C	c #969686",
"D	c #D2D2BC",
"E	c #E0E0C9",
"F	c #E9E9D0",
"G	c #EDEDD4",
"H	c #F0F0D7",
"I	c #BEBEAB",
"J	c #797973",
"K	c #D8D8C1",
"L	c #DDDDC6",
"M	c #98988F",
"N	c #E4E4CC",
"O	c #818174",
"P	c #E2E2CA",
"Q	c #BEBEAE",
"R	c #4E4E4E",
"S	c #828274",
"T	c #EBEBD3",
"U	c #BBBBA8",
"V	c #CDCDB8",
"W	c #4D4D45",
"X	c #A6A696",
"                        ",
"                        ",
"             .          ",
"           ..+.         ",
"         ..@#$%         ",
"       ..&*=-;>.        ",
"     ..,'**)!~{].       ",
"    .^/'(_:<[}|12       ",
"    .3456*789|0ab.      ",
"    .cdef_!9g0hbij.     ",
"    .kklmn9opqrist.     ",
"    .uvwx-}yzbittAB.    ",
"    ..CD!E{FGHtAABBI.   ",
"    .JK7L>ypbitBBBBB).  ",
"    .M!#$NyzbitBBBBBO.  ",
"     .~9P|1qrsABBBB..   ",
"     .Q||0hGHtABB<.     ",
"      R01hGrstAsS.      ",
"      .TaGriss<.        ",
"       .rHis1j.         ",
"       .UstVW.          ",
"        .tX.            ",
"         ..             ",
"                        "]
tb_revert_xpm = [
"24 24 62 1",
" 	c None",
".	c #000000",
"+	c #629DA8",
"@	c #2C3D42",
"#	c #A8C7CB",
"$	c #E9EEEF",
"%	c #C5D8DC",
"&	c #F0F2F3",
"*	c #F9F9F9",
"=	c #E5ECED",
"-	c #7AABB6",
";	c #B1CAD0",
">	c #F4F6F6",
",	c #80AFB9",
"'	c #212F32",
")	c #8DB6BE",
"!	c #D5E1E4",
"~	c #E9EEF0",
"{	c #647F82",
"]	c #EDF2F2",
"^	c #EBF0F1",
"/	c #F2F4F5",
"(	c #45676E",
"_	c #F1F3F4",
":	c #36575F",
"<	c #9EC2C7",
"[	c #294249",
"}	c #2E3B3D",
"|	c #385C64",
"1	c #A4ADAF",
"2	c #EDEDED",
"3	c #E9E9E9",
"4	c #45494A",
"5	c #CDD1D3",
"6	c #F2F2F2",
"7	c #EAEAEA",
"8	c #E6E6E6",
"9	c #AAB6B8",
"0	c #2B464D",
"a	c #18292D",
"b	c #5C8791",
"c	c #C2C8C9",
"d	c #F4F4F4",
"e	c #3B5055",
"f	c #D5DFE0",
"g	c #E3E3E3",
"h	c #DFDFDF",
"i	c #828C8D",
"j	c #1E2A2D",
"k	c #6DA4AE",
"l	c #DCE0E0",
"m	c #E5E5E5",
"n	c #B8B8B8",
"o	c #4B5C61",
"p	c #D6DCDD",
"q	c #ECECEC",
"r	c #A7B4B6",
"s	c #D9DBDC",
"t	c #7D8A8C",
"u	c #2B2B2B",
"v	c #E2E2E2",
"w	c #859597",
"                        ",
"      .                 ",
"     ..                 ",
"    ......              ",
"   .........  ..        ",
"    ..........+@.       ",
"     ..   ...#$+.       ",
"      . ..%...&+@.      ",
"      ..%#%*..*=+.      ",
"    ..-;%***..*>,'.     ",
"   .);!*****.***~+.     ",
"   .{)]****.****^+@.    ",
"    .#=*******/=+++.    ",
"    .(-]****_=++::+@.   ",
"     .<=**_=++[}|+:+.   ",
"     .(-^=++[1234+:+@.  ",
"      .)++:5667890+[a.  ",
"      .b-+cdef3ghi+'..  ",
"       .)+:6jklmno..    ",
"       .|++pqrstu.      ",
"        .0+:vw..        ",
"         .....          ",
"                        ",
"                        "]
tb_save_xpm = [
"24 24 64 1",
" 	c None",
".	c #000000",
"+	c #779FA8",
"@	c #495A5E",
"#	c #BFD1D5",
"$	c #A8C1C5",
"%	c #E4ECED",
"&	c #FFFFFF",
"*	c #EEF3F4",
"=	c #E0E9EB",
"-	c #87AAB2",
";	c #AEC4C9",
">	c #F5F8F9",
",	c #8BADB5",
"'	c #3E4D50",
")	c #94B2B9",
"!	c #CFDCDF",
"~	c #E4ECEE",
"{	c #788A8D",
"]	c #EBF1F2",
"^	c #E8EFF0",
"/	c #F2F6F7",
"(	c #607A7F",
"_	c #F0F4F5",
":	c #536E75",
"<	c #A0BCC1",
"[	c #465E63",
"}	c #4B575A",
"|	c #557278",
"1	c #A4ABAD",
"2	c #EAEAEA",
"3	c #E4E4E4",
"4	c #606364",
"5	c #C6CACC",
"6	c #F3F3F3",
"7	c #F1F1F1",
"8	c #E7E7E7",
"9	c #E1E1E1",
"0	c #A9B2B4",
"a	c #486166",
"b	c #34464A",
"c	c #729096",
"d	c #BCC2C3",
"e	c #F6F6F6",
"f	c #57696D",
"g	c #CFD8DA",
"h	c #DEDEDE",
"i	c #D8D8D8",
"j	c #8C9394",
"k	c #F2F2F2",
"l	c #3A474A",
"m	c #7EA4AC",
"n	c #D5DADA",
"o	c #E0E0E0",
"p	c #B4B4B4",
"q	c #657376",
"r	c #D0D5D6",
"s	c #E9E9E9",
"t	c #A7B0B2",
"u	c #D2D4D5",
"v	c #899293",
"w	c #484848",
"x	c #DDDDDD",
"y	c #8F9A9B",
"                        ",
"                        ",
"                        ",
"              ..        ",
"            ..+@.       ",
"          ..#$%+.       ",
"        ..#$#&*+@.      ",
"      ..#$#&&&&=+.      ",
"    ..-;#&&&&&&>,'.     ",
"   .);!&&&&&&&&&~+.     ",
"   .{)]&&&&&&&&&^+@.    ",
"    .$=&&&&&&&/=+++.    ",
"    .(-]&&&&_=++::+@.   ",
"     .<=&&_=++[}|+:+.   ",
"     .(-^=++[1234+:+@.  ",
"      .)++:567890a+[b.  ",
"      .c-+defg3hij+'..  ",
"       .)+:klmnopq..    ",
"       .|++rstuvw.      ",
"        .a+:xy..        ",
"         .....          ",
"                        ",
"                        ",
"                        "]
tb_trash_xpm = [
"24 24 84 1",
" 	c None",
".	c #000000",
"+	c #252525",
"@	c #A8BA9E",
"#	c #B4C1AB",
"$	c #E1E7DD",
"%	c #838A7D",
"&	c #909F86",
"*	c #484E43",
"=	c #A0AD94",
"-	c #9EAB91",
";	c #B6C4AD",
">	c #BFCCB7",
",	c #A7B69B",
"'	c #BEC9B5",
")	c #656F5E",
"!	c #2B2E28",
"~	c #353931",
"{	c #242622",
"]	c #9BAA8F",
"^	c #9AA78E",
"/	c #98A58C",
"(	c #96A58D",
"_	c #D7DED2",
":	c #A4B398",
"<	c #A2B196",
"[	c #A0B095",
"}	c #97A38A",
"|	c #7C9674",
"1	c #B0C0AB",
"2	c #CED6C8",
"3	c #DAE1D6",
"4	c #BBC4B1",
"5	c #5B6B57",
"6	c #637354",
"7	c #748C6B",
"8	c #94AA8D",
"9	c #8FA58A",
"0	c #6F8668",
"a	c #667961",
"b	c #5D6E58",
"c	c #4D5A4B",
"d	c #485245",
"e	c #738B6E",
"f	c #687B63",
"g	c #5E6F5A",
"h	c #576452",
"i	c #495345",
"j	c #4F5B4B",
"k	c #3F453D",
"l	c #586953",
"m	c #C3CEBF",
"n	c #556550",
"o	c #AABAA6",
"p	c #455042",
"q	c #879B83",
"r	c #424D40",
"s	c #84967F",
"t	c #414A3D",
"u	c #AAB9A6",
"v	c #84957F",
"w	c #080808",
"x	c #84957E",
"y	c #C2CEBF",
"z	c #A9B9A6",
"A	c #414A3C",
"B	c #687A63",
"C	c #C2CDBF",
"D	c #83957E",
"E	c #404A3C",
"F	c #809A78",
"G	c #AEBDA9",
"H	c #51604D",
"I	c #879B81",
"J	c #4A5846",
"K	c #677A61",
"L	c #7D9775",
"M	c #7A9472",
"N	c #788F71",
"O	c #62775D",
"P	c #728A6B",
"Q	c #5E7058",
"R	c #6D8267",
"S	c #697D64",
"                        ",
"                        ",
"                        ",
"                        ",
"       ........         ",
"     +.@#$%&*=-..       ",
"    .;>,')!~{-]^/.      ",
"    .(_':<[=-]^/}.      ",
"    .|1234=-]^/|5.      ",
"    .67899||0abcd.      ",
"     .+effghijk+.       ",
"     .l++++++++f.       ",
"     .lmnopqrstf.       ",
"     .lmnupqrvtf.www    ",
"     .lmnupqrxtf.wwww   ",
"     .lynzpqrxAB.wwww   ",
"     .lCnzpqrDEB.wwww   ",
"     .FGnzHIrDJK.www    ",
"      .LMNOPQRS.ww      ",
"       ........w        ",
"                        ",
"                        ",
"                        ",
"                        "]
tb_undo_xpm = [
"16 16 8 1",
" 	c None",
".	c #000000",
"+	c #8F431E",
"@	c #803C1B",
"#	c #8A411D",
"$	c #954620",
"%	c #733618",
"&	c #5C2B13",
"                ",
"                ",
"     .          ",
"    ..          ",
"   .+@...       ",
"  .#$##@%..     ",
"   .+#...%%.    ",
"    ..   .&.    ",
"     .    .&.   ",
"           ..   ",
"           ..   ",
"           .    ",
"          .     ",
"                ",
"                ",
"                "]
tb_up_arrow_xpm = [
"24 24 49 1",
" 	c None",
".	c #000000",
"+	c #B1C7AC",
"@	c #3A5934",
"#	c #181818",
"$	c #EEF3ED",
"%	c #59814F",
"&	c #CBDAC7",
"*	c #DEE7DC",
"=	c #759B6C",
"-	c #445840",
";	c #F0F4EF",
">	c #D7E3D5",
",	c #84A778",
"'	c #537C49",
")	c #C9D8C5",
"!	c #E5ECE3",
"~	c #7EA476",
"{	c #759C6D",
"]	c #4B7040",
"^	c #F1F5F0",
"/	c #EBF1EA",
"(	c #E4EBE2",
"_	c #85A879",
":	c #86A97C",
"<	c #CEDCCB",
"[	c #83AA7C",
"}	c #749868",
"|	c #3B5E31",
"1	c #EFF3EE",
"2	c #88AC80",
"3	c #82A87B",
"4	c #D4E0D1",
"5	c #EDF2EB",
"6	c #87AC7D",
"7	c #80A776",
"8	c #749A6B",
"9	c #37592F",
"0	c #F3F7F3",
"a	c #F4F7F4",
"b	c #83AA7A",
"c	c #5D8554",
"d	c #E1EADF",
"e	c #FFFFFF",
"f	c #9DBB90",
"g	c #9ABB8F",
"h	c #90B387",
"i	c #3F6534",
"j	c #2B2B2B",
"                        ",
"                        ",
"                        ",
"                        ",
"           ..           ",
"           ..           ",
"          .+@.          ",
"          #$%.          ",
"         .&*=-.         ",
"         .;>,'.         ",
"        .)!*~{].        ",
"        .^/(_:'.        ",
"       .<///[,}|.       ",
"       .;11123_'.       ",
"      .45^11[6789.      ",
"      .;0a112b67c.      ",
"     .deeeeefggh[i.     ",
"     ......j.......     ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        "]
drilogo_xpm = [
"300 215 91 1",
" 	c None",
".	c #161602",
"+	c #164E02",
"@	c #85513F",
"#	c #4E833E",
"$	c #6A625A",
"%	c #669252",
"&	c #7AA5B4",
"*	c #3AAE26",
"=	c #86B276",
"-	c #BEB4B3",
";	c #B6CEAE",
">	c #8E1206",
",	c #5292EA",
"'	c #2E8E12",
")	c #37822A",
"!	c #DFD7D3",
"~	c #6EAAF6",
"{	c #9F3422",
"]	c #569AFA",
"^	c #D9E5F0",
"/	c #1AB602",
"(	c #0A5652",
"_	c #1E6232",
":	c #4EB22E",
"<	c #D9F3D9",
"[	c #5AAE46",
"}	c #B5230D",
"|	c #A6CE96",
"1	c #AC4E3F",
"2	c #F68472",
"3	c #2E78E0",
"4	c #66B256",
"5	c #40EE15",
"6	c #E9F8EC",
"7	c #B63626",
"8	c #B64F3C",
"9	c #926E62",
"0	c #76CE66",
"a	c #4ECE2E",
"b	c #F2EEE7",
"c	c #C81906",
"d	c #B26B5E",
"e	c #35838F",
"f	c #D5513D",
"g	c #72966A",
"h	c #BEF7AA",
"i	c #FABCB1",
"j	c #4E8ACE",
"k	c #6ED252",
"l	c #CE7266",
"m	c #BB8674",
"n	c #8AD272",
"o	c #CC260D",
"p	c #56D646",
"q	c #F5FBF5",
"r	c #26BA06",
"s	c #66D63E",
"t	c #EA5540",
"u	c #4088EC",
"v	c #2269C7",
"w	c #96B8DC",
"x	c #265A66",
"y	c #FEFEFD",
"z	c #6E1606",
"A	c #EDE9E6",
"B	c #FAAA96",
"C	c #2A520A",
"D	c #3F96FA",
"E	c #56DA36",
"F	c #A9FD93",
"G	c #18A804",
"H	c #D03215",
"I	c #28CF06",
"J	c #D53A26",
"K	c #42D826",
"L	c #0F55B2",
"M	c #C9C8C6",
"N	c #C1DBEE",
"O	c #ADA39F",
"P	c #4B1B05",
"Q	c #4E76A2",
"R	c #EB6954",
"S	c #38B116",
"T	c #1F7809",
"U	c #4FEC2A",
"V	c #803226",
"W	c #649AE6",
"X	c #37D112",
"Y	c #6AF54A",
"Z	c #85F769",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyybyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqyyqybyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqyyyyyqqyqyyqyqyyqyqqqyqqqyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqyyyqyyyqqqqqyqyqyqyqyqyyqqyyqqyyqqqyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqyyyqy6yyyyyyyyqyqqyqqqqqqqqqqqqqqqqqqqqqqqqqqqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqyyyqyqyqqqqbqqqb6qA66q66666666A66A6A66A6<6A6A6<A66666bqqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqbqqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyy6qqqiB2B2BBBiBBiiBiB2BB2B2BBBBiiii!i!!iiiii!!!!!!!!AAAAbbbbbqqybyyyqyqbyyyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyq6h<hh<Fhh<<hhhhhFFFFFFFFFFFhhFFFFFFFFFFFFFFFFFFZFFZZZFFFFFFFFFFFFFFFhh<h<6666q6qyyyyqyyyybyyqqyyyyyyyyyyyyyyyyqyyyyyyyqyyyq6yAA;wwwwwN^ybyyqyyqyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyqqb-d1JffRlRddlll8ff88ff881f7888888dfdlld8fd8ffl8fddlddlm2O-Bi!bbbyqyyqyyyyyyyyqqyyyyyyyyyyqqyyyyyyyyyyyyyyyyy6<FhFFhhhFFFFhhFhFFFFFFFFFhFFFFhFFFFZZZZZZZZZZZnZZZnZZ0ZZYnnnnZnZnnnnZnZF|h|hh<<6qqqyyyyyyyyyyyyyyyyyyyyyyyyyqqyyyyqqyyqqyq6^w~wW]~~~]w;qyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyybyqqB7}8JtfRtRRtRttJooooooooooHooHJHHJJfJJHoooJoHHooHooHHHJoHHHJJttR22iibAqqbyqyqqyyyyqyyyyyyyyyyyyyyyyyyyyyqyyyh|nZZZZYYYUU55UUUUUU55U5YYYYYYYYYYYZYEEUUUUUEUUUEEUEUUUaUEUEUUUUEUUUUUUEUUUUUUYYYZZFh<66yqyyybyyyyqyqyqqyyqqyqyyqbyyqqq6NN~~u,3u,]]]~~]w^yqqyqybyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyqbb8{78fRRRttftttJHoooocooooooHooooHffffH7ooH}o}oHoocoooooHooHoooHH7J18mO!byyyqqqybqyyqyyyqyyyyyyyyyyyyyyyyqyyqnnZnYZ5EU5U555555555U55555Y5YYYYZZYYYUEUUUKUUUUUUUsUEsUEKUEUUEUpUEUUEUUUUUsUEEEUsUksnZ<6yqyyyyqqyyyyyyyyyqqqqyqyqyyyANw&Wjujuuuu,u,,W~~W!yyqqbyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyybbf7JftflfttRtttfHoooooooooooooooo7fJJJHoc}H}}oooHoooo7ooooooo}}oHooJHJHHt2ibbqqyyy6ybyyyyyqyyyyyyyyyyyyyyyyy6|=0kZsSKUU555555UUUY5UYUYYYYYYYYZZZZZUUEUUUUUUEUUUUUUUEUUEUEEUUEEUpUKUEKUUKUU5U5UKUU5UUUZF66qyyyyyyyyyqqyqyyq666<Nww]],3uuu333u]wDuu]]WWwyqqqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyqyb!{7ftttffttttftJHoooocooooooooooJfttJfJo}ooooo}}ooooooo}oc}ooHHHHoocHcoJJ11mBbyyybyyyyyqyyyyyyyyyyyyyyyyyyyqAn=kksaKK5YYYYYYYYYYYYYYYZZZZZZZZZZZZZYYEUEUUUUUUUUEUXEKUEK5KKEKKKKKKKKKKXUXKXXXUK5KK5UKUkY;6qqyyyyqqyyyyqyyqq^Nw~~Duuu3Qu3Quu3,|N~uu,]WWw6q6yqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyqqyAffftRtRfRttRttfooooHoooocooo}cJJtttfJJooooooo}H}o}cooooooco}c}ooooooHoooooHHt2!byyyqbqyyyyqyyyyyyyyyyyyyyyyq=400[:KXUZZZZZZZZZYZZYYYZZZZZZZZZZZZYYYUUUKXKXUXaKKXaXaXaaKaXK:KaKXSKSXIXXIXKXXXKXXKXU5X55UYh<qyqqyyyqqq6^Nww]]uuuuu3uuuu3u3Qv3]|Duuu]]]w^qqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyqyy!88JfflffltlttfoooooooooooocooooJttttt7ooH}}oooooooooocoooooccooocococooooooo7JlOAqyyqyyyqqyyyyyyyyyyyyyyyyqbn=40:'SXXYsYEYUUKK5KKKKKYYYYsYYYsYYssUUEEXXXXXIXSaXSXKSXSXX:XaXXK*KSXaXrXrarIrXIIXKXIXI5I5U50h6qqqqyq6^N&OW,3uu3e3u3uu33333Lv33D~WD3D]W,W<6qyyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyy!J8H7HJftRtfRtfHooocooooHooooHo7JftttJJoooooo}ocooo}ooooooHooo}ooocooocooHooHoHJJlBqqqqyyqybqyyyyyyyyyyyyyyyb==[=''XrIIIKIXIX5I5IXXXXXKUUEYEYUUUUKUEXrKaIIXXXIXXIXIXIXIrXrXrrSXXXIXXXXXXXaXrXIIIXXXXrIII5EUZ^yy6^wwuDuuuuu33uu3j33Q33vvv3v33u~Wuuu]W]WNqqyyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyb!77}}H7JtttRftJHJooHcoooooooocoHttttfJHo}oooocooooocoooHo}oooHooocooocoooooooHooo77BAyqbyybyqyyyqyyyyyyyyyqyb===4'_r/5II5I5I5I5IIII55KUUEUUUYUUUUUKKIKXIrXIIXrXXrXrXXXrXXXXIIrGXIarXrXrXrXraIIrXI*XIGIIIIaX0FyqNw]uuQu3u3uuj3vuQ333vvQvQv3v33~~]3u,W]W;qqbyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyb!H}}H7JftfRRttfJJJHooooHcooHooo}fftffJJHoo}ooooocooocooooooHHJJoooocoooccoooooooooHJtB!yqqyyyyyyyyyyyyyyyyyyb=g==)TSrIIXIIIIII5I5I5555UKUUEUYUUXUaUXXXXXXrXrXXXXXKIXXXXrXrrIrrIrXXraXaIaI*IXrXXrIrrIII/III*IIh|ej,uuuuu333333L3vvL3vvvvv3vv33W~DQuDWW,wqqybyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyybM}7}HJJftftttfJJJHooooooHoooHo7JftRtffH7oooooocooooooooooooHHJHo}coooococoooHooHHoHJolmAbqyyqyyyyyyyqyyyyyyyb==g='_/III5I5I5IIIIII5K55UUUUUUUUUXXXKUXKrXXXXXXIIIXIXXrIXXXXKrXXXrrIXXKXKrXXrXIXIKXIKIXIXrSGIG/%x(e,uuu333333Q3v3vvv3v3v33vQvv3]~Duu,~]W~qqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyqqy-ooH778ttftffJJHoooooooooocooooHttttffHooccocoooocooooo7o}HHJJHoooocoooooooooooooHoJJot2BAAbyybbyyyyyyyyyyyyqn[4=%'XSIIIII55II5III5555EUYYYUUXKXIK5UUKXXXIIXIIrXIIIXXrXrXXXXrXIIXIrXKKKXXXXrIIIIIIIIrIII/I/GGTTLxu3u3uvQ3333vLQ3LQv3Qvvvv3v33Q~],uD~WWW6yyyyqyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyqyb-oH}}JJftRftftJooocooocHoooccooJtfRttttoococoooooooHo}oHoHJJJJJJoooococoooocooocooooooofRBibqyyyyyqyyyyyyyyyy=%[4_T//III5IIIIIIII5555U5UU5YUU5IKXKX5UUXrXXIIXXXrXrXrXXIarXrXIIIXIXIXKKXXXXIIIIIXrIrIII/rI/GGG(T(euuvuQj3j33vv3v33vvvv33v3Lvv3uWWuuuWWWW<qyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyqqy-oHo}HJftfRfffHHoooooooooooHooJJtttttfJHocoococoooccoccoocooJJJJHocooococoooocooooooooJoJRRi!qyyybyyyyyyyyyyq=:%%#_S/IIKIII5II5I55555UUUUUUUUIIIKK5KUUIIrIIIIIXKIIIIXXrXXXXXrXrKIXXXKKKKKaIrXrXIIIXIIr/r//G//e((333vv33vQ3Qv3v3vvv3QLv3vvv3v33]]uuuWWW]Nbqyqqyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyqyq-}o}7}JJtftRtHJooooHoooooooooHJJfRfttJJoooooococcooococococHJJJJoooooooooocooooooHoHooo7HfRB2!byyyyyyyyyyyyyy=%%='Tr/III5IIIIIII55555YUUYUYYKXKU5KUK5XXXIIIIIIIIIIXIXIIIIXXXaIIXXXKXKKEKaIaXIIXrIIIIIII/GG/G/)T(xQv333QQ333vvvv3v3vv3LvQL3vv33]~,uuWW]]Mqyyqqyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyb-c}oJHo7ftffJ7ocHoooooocooooooHfttftfJHooooocooocooooooooocooHoJJoooococooooo}ooocoooHoHJJfR22iqAyyqqyyqyyyyyn%%%)_SrIIIII5II5IIII555UY5U5Y55U5U5EUUaIIIXIIIIIIIIIXIIIIIrIXXKaUa5XKKKKXXKUUXXrIIIIIrIX///GGGGI_(Lu3vjj3v33vQvvvvvQvvvv3vvvvvv3u]33uu]W]&yyyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyybO{ooooo7ftftfoooooooooooHoooo}HJfRtttJHooooooccocoooooooooooHHJJJHoccococooooocHoooooooooHHt2BBBAybqyyyqqyybb=#%gTTSSII5IIIIIIIII5555UUYU5YYUUEU5KU5UIIIIIXIIIXIIIIIrIXrXXXaXIX5EEUEEKaKEKXrIIIIIIIIII///GGG/GT((v3Q33QuQ3vvQvvvvvvvvvvvvvvvv33W]uDu~],w6yyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyybB}}oooo}ftfJHooooooooooJoocoo7HfJtttttJHocoooooooocococoooooJoHJJJoooocHocoooco}oocoocHooHHHt2BiiAyyyyyyyyqyy=%%%#_SSIIIIIII5III5555YY5UUU55555XI5KKKKIIIIIXXIIIXIIIXIIIKXKKXKKKKEUUsaEUUUXIIrIIrIrIIr///GGGG*'((x3jvu33333vvvvvvvvvv3vv3vv3v33u]uuu]~]WNyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyqO}7oooo7HfffJoJoooooHHHHocc}}ooH7JftHtHoccooccccccooooooccooooHJJoococoooo}oocoooHoooocooHHHJ8liB!Ayybqyyqqyqn%:%TTSGIIIIIIIIII555555YUUYY5IIII5X55XX5IIIrX/rIIIIIIIIIIIKXIXKrXXEUKEEKaUErXrIIIIIIIIII///GGGGGTL(LvQ3v33Q3uQvv3vvvQvvvvvvvvvv33WDuuuD,WWNyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyybOc}ooHo7fttJJHoooooHHJJHccc}77}7778fffHocoo}c}}}oc}ccccoooocc}ococcoooooocccooc}o7cooooooJHJJHJ2BBi6yyqyyyyyym[%%_T)*IIIIIIIII5555555Y5U5Y5XII5I55IK5KXIXIXIIXIIIIIIKXXXXEapUapYEUUYEaaaaXaIrIIIIIIIII////GGGG'((xv33Q333u3uQ3vvvvvvvv3vvvvvv33uuu3uuWWWwyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyqAm}oooHoHttttJJocHoHJJJJH7J777}o>7778fffJHH}H7o}H}}}}}}o}cco}cHooocoooooooHoccccocooooccoooHJHHHlBii!byyyqyyyq|%%m#TG'IIII5IIII5555555Y5YU55555I555UUU55K555555K555K5KXaX*XaaXaaaaaa*XaXaXKXXrIIIrI/I/////GG'GG/((QjjQujuvQ3uQQ3vvvvvvvv3vvvvLv3u]uuuuW]Wwyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyybm}7oo7H7fttfJfHoooJtJfHHHH}>zzzPzVzV@{{{VV{V{>V}{{{7777}{}{}}}oooooooHcooooJooooooocooooooJHHoH7tiBi!byyyybqq|%%%T_'G/IIIIII5III555U5Y5UUY5555K5UpUYYpaKXIXr*:*:****S**')')[T#')'''''r*aaapKIrIIIIIII/G//GGGGGG(TLjvjuu333uu3vLLLLLQLvLvvv3vvv3uDuDuu~]W~qyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyAm}oooooJJJJfttJJooHtJfJJJ7>zzzzzPPzzz>zz>z>zzzzzzz>z>>V}{77}{ccoocoooooHococcococooooocoocoJHH7}{RiiBAbyyyyqq|%%%#TG*/IIIIIIIIIII555Y5Y5Y5U55UUpX*S*T'''T''GG'G'')G''*)*[p4000['_'_TTT'*:XaKKIIrII/II///GGG'G'G__xxjjWj33Q3LLLLvvLLLLLLLvvvLvvv3]u3u3WWW]Ayyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyAdoooooHHHJHHJftJH}Jttf}tf>VzzPPPPPPPPzPzzzV{VVzVzzzzzzzzzz>{{7ooocoocoocoooooooocooocoooooooJHoH>7BBii!yqqyqqn%%#C_*'GIIIIIIIII5I55555Y55Y55Us*''%%g%%%===O|;M;^<^6qbqqyyyyyyq6%T'_TTTT_**aKaIIIrII/r//GGGGGG'GTTLeD]]ju333vLLLvQLLLLLLLLLLLLLv3uuuDu]~]]Nqbyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyqyqd}oooc7oHooHJfftHJHttf7fH>V{>zzPzPPPPPPPPPVVVV@VV{VV{VV{V>>zz>}}ooccocooooooooooo}oooocoocoooHHHHVRii-ibyyyqy|#$%TT'G/IIIIIII555555Y555Y55UUK'*0F<h<66q6q6q6qqqqqqqyyyyyyyyyyqq|eTTT_+TT_T'SaXXI/rIII//GGGGG'GG__((3juv3uQuuQvLLLLLLLLLLLLLLLLv3uuuuu,WW]Nqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyqqAdH}oo7ooooo}Hffttffttf1J}{VV1VVVVVzzzV>zzVVVVVVVVVVVVVVVVVVVVzPV{7}oococcoHcooococoooooocooooJHHH>}BBiB!qyyy6;%###C'GG/IIIII5IIIII55Y55Y5UUUI%h6<qqqqyqyyqbyyyyyyyyyyyqyyyqyyqy6$_$')T_T+T'GaKKIII/r////GGGGGGGTT(xv3Quu333juuQ3vLLLLLLLLLLLLLL3uuuuuD]]]wqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyb9ocooHo}oJo}ofttttttt28H{{11@{@@V@VVVVVVVV@O-i-iOMmOmm9d9d@@VVVzz>}ocococoHHoooococo}HooooocootHH7>1iiBBAyyyy|#$#__'G/I/I/II5I5IIII5X5I5KKYUS|Aq6qqyyyyqyyyq6yqyyyyyyyyyyyyyyyyqm))))TTT_T_G:KUa/I/I///G/GG'G'G'T((LvuQuju3j33u33QLLLLLLLLLLLLLvuuuu3u]W,w6yyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyb9cooo}Ho}oo7HffRtRfR2im7>{111@1VV{V{V{@VV$Mbbqqyyyyyybyqyyybb!!-dVPV{ooooocoooooHooocoo}ooooootoHHcVRBBOOqyyyh###$C':IG//////III5IIIIIIIIXYpaqqyqyyyqyqyqyqqqyyyyyyyyyyyyyqyyyyqO#$())_)T'TT*XKU/GG/G//GGGGGG''T'((Lvj3u3uujuuuuuuuvLLLLLLLLLLLL3uuDuuD]]&^byyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyybA@oooo}oHoo7oHftRRRtRRi2J>1{1{{8{@V{V{V{@@mbbyyyyyyyyyqyyyqyyyqq66A@zV7oocooo}oocoocoo}oHoooocooHJJHVz12i2Mbqbh$$#TC':Gr//GGG/5IIIIIIIIIIIUYXYyyyqybyyyyqqqyyqyyyyyyyyyyyyyyyyyqqOT#_)#))')TT'SKUSGGG//GGGGG''GGG'((xuQuj3uuQ3u3uu3juj3vLLLLLLLLL3uuQu3]]W&^byyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyybyA1ooooH7ooJo7fftRfffR2i2f}1111{1{111V{1@1@byqyybyyyyyyyyyyyyyyyyqqyqmP{Voooccooooocooo}ooHHooocoJtttf}VP@lmbyyh%C$TC'''GGGrGG/I//II555IIII5EaZqy6yyybyqyyqyyyyyyyyyyyyyyyyyyyyyy6|))#)_#_))T_'aaUaGGG///GGGGGG''T'(_L33Quuuu3uuuuuuuu3uu33vLLLLLL33D3uu,]~WNyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyA@ooooooooJJJfftRtlfR2i2f7V1{@{V1{{1{7@1VdbyqqyyyyyyyyyyyyyyyyybqyAqAO>Vo}coooooooooococ}HHoooooJRRtff{VPV9Bqyh$#$)CT*G'SGGGGG//I5IIII55KIXppZbqyyyqyyyyyyyyyyyyyyyyyyyyyyyyyyqq6MT#T#)))))#TTSKKEGGG/G/GGGGGGG'''((vuuju3uuuuu33u3uuuuuuu33vLLLL3uuuuuD],Wwyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyqy!8oo}oooooJHttRfttflR2!2f{111111{V{V{{{{Vdyyyyyyyyyyyyyyyyyyyyyyqqqyyb-VV{oooooooooooHoooo7o}oooJtBJJH{VVzV@!yM###CC_'G'GGGrGGrGrIII/I/I/II5*Fqyyyyyyyyyyyyyyyyy6yyyyyqqyyyyyyyy6|)#)_#T$_#T)_GaEE/G/GG/GGGGGGGGTG__xxuu3juuuQu3juuju3uuuu3u3uu3L3333uuu]],wyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyb!@ooooooooo7fRtttRtfR2iRJ}1111111{7{V7{{@dyyyyyyyyyyyyyyyyyyyyyyyqqbyyAOzVo}oooooooooooo}HJHHH}o7t2RfHV>PVPPmy<$$C@C''GGGSGGSG/G/I5III/G/II5[Zyyyyyyyyyyyyyyyyyyyyybyyyyqyyyyqyqb=)#)'))#))))TGXUErGGG/I/GGGG'GGTGT+(L3Quj3uujuuuu3ujuuj3u3333uu3v3DuuuuD],~qyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyy!8ooocooHoooftfRtttRR2!28}1{1{111@V7{V{{VmyyyyyyyyyyyyyyyyyyyyyyqyyqyyAblPV{o}oooooooH}oooJJJHocoJ22tJ1}VVPzPbh##$C+_'''GGG/GGGG//IIIIG/IX55rFqyyyyyyyyyyyyyyyybyyyyyyyyyyyyyyyy6=[')#))$%')''*XUp/GG/rrIGGG'G'G'T_TLxuuu3u3Quujuuuuuuuu33,3uuuuuv3uuuuu,],~<qyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyi{7ooo}oooooJttfttlfR2Bmf7@11111{1{{{{7{Vlyyyyyyyyyyyyyyyyyyyyyyyqyyyybb!1>7oooooo}ooooooooJ7o7ooHJ2Rff}zzVzPO6$))$C''GGG*GSGSGrG/////G/II55*Zyyyyyyyyyyyyyyyyyyyyyyyqqqqyyyyyqy<=4[[''')T#''_GaKXrGG//I/GGGGG'GG'T_x(3jujuujuu3uuuuuuu3u3uuuuuu33v3uuuuD]]W^yyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyq!1ocooooooHo7fftRflfR2Bmf}18111V@17{V11{Vlyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy!VV}Hoooooo}o}oo}}HJHHJocJt2tH}PzVV.V<#$CCCT'G*GGGSGGGGGr/IGGSr/r5I*Zyyyyyyyyyyyyyyyyqqyyyyybqyyyyyyyqqh=k4[[[%')#)''GaKXIIr/r//GGGGGG'GGT%L(3Q3uuuuQuuujuuuQuQu3uuuuDuu3v33u3uD]],M6yyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyqiVooooooooooHo8fRtfRR2Blf7d111181{V7{1{VVmyyyyyyyyyyyyyyyyyyyyqyyyyyyyyyqqmz}}o}H}ooooo}oooo7HJJooHt2tHJ{>PzPP=$#_.C_'G'*'GG*GSGrGGI/G*GGr5I*Fyyyyyyyyyyyyyyyyqqqyyyyyyyy6yqqqyq|=00k[4[#%''''GSr*IUIGI//GGGG'GTG'[|((vuuuuuuuj3uuQuuuuuu3u33uuuu333uuuuu]]]wqyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyi{oHooooHoooooHtttftR2Blf7111{{1{{{{{V{{1myyyyyyyyyyyyyyyyyyyyyqyyyyyyybqyAVV{}Hoooooooo}Ho}oHHJooHtBRfJ1{zPPP$$$CC+_'S'GG*GG*G*S'GGGS/G/I5I)Fqyyyyyyyyyyyyyyyyyyqyyyyybyqyyyq6<00000044[[%'''GKXXrKI/G//GGGGG'GT'jh((xQuuuuQuuQuuuuuu,uuuuuuDuuuu333Duuu]W]w^yyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyqiVoocooocoooooftffftR2BR7711{{{{V{{{1{{7@ByybyyyyyyyyyyyyyyyyyyyyyyyqyyyyqAO>{o}oo}ooooooo}o}o}oocoottff{}zPzPP#$_PCTTGG'GS'GGGSGGGGSGGGGI5I*Fyyyyyyyyyyyyyyyyqyyyyyyqbyyyyyyy6hn0k0=00k04[[G'/:rXIII/I///GG'GG/''|6x(Ljujuu,Quuuuuuujuuuuuuuuuu3uv33Du3uu],WAyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyB{coooooooooooJff8Jft22R{{1{{{{{{{V{V7{11OyyyyyyyyyyyyyyyyyyyyyqybyqyyybyqyA{V7}7}co}ooo}ooo}oo}ccoo8227f{zzzP.$C@+.T'SGGGGGG*GGG*GGGGGGGG55GFyyyyyyyyyyyyyyyyybyyyqyqyyyyyyyyhZ0sYa00kkn404*S/XXrrXI/IIGGGGGG''''Nqj_LvuQuuuu,uj3ujuuu33u33,uuuDu3333u3u,]]WNqyyqyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyqB{ooooooooooooJHHJJJf2Rf}}11{V{{V{{71V{{{-yyyyyyyyyyyyyyyyyyyyyyyyyyqyyyqqqqlz}}o}oooo}ooo}o}}ooocooRi2fJ}zPPz.PTC.PT_S'GSGGGGG*GGGGGrG///5I)FyyyyyyyyyyyyyyyyqbybyyqyyqyyqyyqFnk00k00snk00[''*KaXXGGIrI/GGG'GGG'*6qg(xvuuuuuQuuuuuuu,uj333uuuuuuu333uuu3u],Wwyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyqBVooooooooooHooHJ7JfJtto}{1{{1{7V{V{7{{1VByyyyyyyyyyyyyyyyyyyybbyyqyyyyyqyby!V{{o7JJccoo7ooo}o}}oo}cHB2RJ7zzzPPz$..+T'rrGGGGrGG/G//IIIIXII55*hyyyyyyyyyyyyyyyyyyyyyyqyqyybq6<hZ0YYsYZkkkkkk['GXXKXK////IXIGGGGTG(kyqh_xxjuu3uuuju,uuuuu3uu3uu3uuuu3v333uuu],Wwyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyybB{oooooooooooooH}cotftf7{}1{{{{{{7{{@{{{@iyyyyyyyyyyyyyyyyyyyyyqyyyyyyyyqyyyA@>{}Jtoooooo7oooo7}cooo7BBfHozzPP.P$_.P_TS//SrrIIXXUKK5UU55555I%Fyyyyyyyyyyyyyyyyyqyyyyyyyyyy66h|ZYZY0Uk0npnksS'a/aIUYKIIIr/IGGGG'GTFqqNxLvQjjuujuuujuujuu3j333u3uuuuDv33uu3uu]]~yqqyyqyyyqyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyb2{oocoooooooooHH}HooJR2J>71{{{{{V1V7@{{@{iyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyybbO>7{JJooo}HoH}oooo}oo}ooRifHH>zPzzPCP._T_Kr/5UUUU5555555555555I#Fyyyyyyyyyyyyyyyyqqqqyyyqyy6qhFYUZZsYZY0k0ZY0KGXXIXXUYUIrIG/GGGGG''%<qyq$((3uuuujuujuujuujuuuuuuuuuuuu3v33D3u]]u]qqqyqqyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyq2{ooooooooooHooH7HooHJfH}}{{{{{{{{{{V{{{Viybqyyyyyyyyyyyyyyyyyyyyyyqyyqyqyyyy!{V}7J}Jooo}ooooooocccootil}7{>PzPz+P+P_TrXXU5555555555Y555555I[hyyyyyyyyyyyyyyyyqqqqqqyyyq6<FFZZsYYYsYZZY0Y0*GrKXKUYZK*IGGGGGGG/T'|6yqqj(Lvjuuujuujuuuuuuu,uuuuuDuuuD333u33u3]u,^yyqyyyyyyqyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyqm{ooocooooocHoco}}}c}Hoc{{@{{{1V{V7{{{{{V!yqyqyyyyyyyyyyyyyyyyqyyqyyqqqqqqyyyb1}77}}Ho}oo7oooocooooooti2ooV}zPzPP..C_T*XXXIXII5555555555555I:hyyyyyyyyyyyyyyyyyyyy6666hhhFZZZZZ0Y0kaZYYZYaGIKUKIUYY5IaGGGGGGGGG/^qqqyO((Quujuuuuuuju,uuuuuj33uuuDuu3333DuuuuuuNyyqqyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyym7oooooooooooooc}HoooJRH>}71{{{{{{{V{V{V{!yqyyyyyyyyyyyyyyyyyyqqqybybyyqyyqybql>{}7o}ooHoo}oooooo}o}Ht22HH>>zzzz.P.++'rrI5III5I5555555555555[hyyyyyyyyyyyyyyyybb6^6hhhhhhhFFZZYsYpp0ZkZ0EGSXUUIIUUaI*G'G/GGGG/)Uqqqyq!L(vj3,ujujuuuuuujuuuuu3uuuuuD33333uuuuDjwyyqyqyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyR}ooooocoooooooooo}oJtRH>V71{{{{{{{7V1{V9!bbyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyiP7}}co}o}H}oc}}oo}oooco2Bto{>PPPPPP.PC_SSIK5I555555555555555I*h6qq66666<<<hhhFhFFFFFFFFhFFhFhhZYZZYpsY0pYG*asYUI5KX*r//G/GG'GGG)^yqyyyb)(xj,jujuu,u,u,u]u,uu,u3juuDuuv33uu3uuu3O<yqqqyyyyqyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyR}ooooooooooooo}ooooot2J>71{{{{{{{{{{{{7$!yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy!V>}}7}oooooooo}oooooocH2BJH>zzzPP.P.PCT'X5555555555555555555I*F6<<<h<hFhFhhFhFFFFFFFFFFFFZhFFZZZZsYEZYaa*GaYZYKIUpKI*//I/GG//G'|6yqyyyb3(LQujujuuujuuuuuuu,uuuuuuuuD333333uuuuuW<yyyqqyyyyyyqqyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyR{ooooooooooHooo}ocoJ2RJVV7{{{{V{{{{{V{{@!yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyb@}}o}o}o7c}ooH}ooooooootBto}>PPPP.P.+CT'XUY55555I5555555555KI*FFFFFFFhFhFhFFFFFFFhFhFFFhFFZZhFhZZZYYYEKSSaUZZaIUUUIG/G/G/GG*G'X^qyqyyyyjxxvuQu,ujuuujujuu,uuuuu,uuuDu33u3uuuuuuj^qyqyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyybblooooooooooooocoHooccofc}V{V{1{{{@{{{{{7$AbyybyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyA9>7}}}o}oH}oo}oooooooccfBR7}zzPPPPP.PCTTr5YY5Y55I55555555555I*ZFFFhhFhFFFFFhFFFFFFFFhhFFFhhFFFZZZYYYUS/SaZhZKIEUUpX///G///GG'*Zqqqqyybqw(x3,jujuu,juuuu,uuuuu,u,uuuu3D3uuu3u3QjjNyqqqqyyyyyqyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyt{ocooooooooooooooooJJJ}>}{{{{{{{{{{@{{{@byyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyO>7o7}}o}o}ooH}o}ooocccJ22c}>PzPPPP..T_':U5YY5YYY55555Y55555IrZFFFFFFFFhFFhhhhhhFFFFFFFFFZZFZhFZZZUr/rIEZZZEXUUEUUKI/G//G/ITG&qyyqqyyyyNxLxuuQ,Quuuuj,uuu,uu,uuuuuuD3u333u3uuuuQwqqyyyyyyyqqyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyqfooooocoooooooooocooott}z>{{{{{{{{{{{{V{9AyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyAO{7JoJooo}H}oo}ooocooooJ22H}>PPPPPP.P+T'rY55YY5YY55555555555I*ZFFFFFFFhhFFhFhFFFhFhFhFFFFhFnZZYaX/G/5YYYZZaKEUUpUU5IGGG//GG'a<6yqqqbbyy<$LxQ,jujujuu,ujuu,,uuu33,u33333333u,3uuuwqyyqyyyyyyqyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyf{ooooooooooooooooooHJJczV7{{{{1{V{{{1{{9bbyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyb-}1H7o}oo7ooc}H}7oooooooR2Ho>zPPPPP..CT'SU5UYZYYY5Y55Y55Y555I/UFhFFFFFFFFFFFFFFZFZZZZZYYEUaX/GGrIIaUYYYYYUXKUUUUUKU///G//GG%hqqqyqqybyyqgxLQuujuujujuu,uuuuuuQ33D,33u3333u33uuuu~6qqyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyqqfoocoooooooooooooocoJJJc>}{{{7V{{1V{{V{V9byyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy-{8JH7}}oo}oo}o}oocooccoR2HccPzzPPP..+_'XYYYY5YZZY5555555555IG/ZFFFFFFFFZhZZZZZYsYaaX*SSSrrIXK5U55YYYYYKUXUUUEUK5U5I/G/G/G/F^qyyyqqyyyyqO(L3juQuQu,ujuujuujuuuuuuuuuDuD333uu3uuQW6yqyyyyyyyyqyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyAJ{ooooooHoooococooooJto>>V{{{{{{{{{{{V{{9yybyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy!{{JoJooo}ooooo}ooococoot2JoczPPPPP..+T'aYY5YYZYYY5Y555555555IIpZZZYYYEEKXrrrrS/IIrIIIX5555555555U5YYUKU5UUUUUUU5Ua/GGI/G%|yybyyyqyyyyyyML(vjj,uuuQvuu,u,uuuu3uuu333Duu333uuuuuu3^yyyqyyyyyqyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyAfoooooooooooooooooocotHc>}7{7{{{{{V1{V{Vdyyyyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy!V{}}}}}H}}o}oo}oooooocoJ2JccPzPzPP..CC'XYY5YYYZYY5Y5Y5Y55555rI*XaI/XrrXrIXXX555X5UU5555555555555K5XKXU5UUUUUpU55EK///IGX|6yyyqqyqqyyyyyAxxvj,juQuuujuu,,uujuu3uuj,uuuuu3333u3uQu!qyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyAJ}ooooooHcoo}oooocooHJJ>z>{{{{1V{{{{{@{VOAybqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy!{V}7oooo}oooooo}ooooccot2JoczPzzPP..+T'SUY5YYYYYY555555Y5Y55IIIIII555555555555UU55555555555KXXIXK555UUUUUUEUUUpYUXGG/*%|qyyyqqyyyyyyyyyyQ(vQ,uuuuQuuujuu,uuuuuuuuuuuuD333Du3u3uuw6qyyyyyyyyqyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyy!f}oooHoooooooooooocootoc>}1{{{{{{{{{{V{>ObyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyA{Vo}}o}o}}occooocooooocJ2Hc}VPzPzP..++TS555YYYYYYY5Y5Y5555555I5555555U5Y5555Y555555K5I5II555555555UUUUUEUUUKUUKpEI//G*h^ybqbqqyyyyyyyqqqj(xjQujjuujjuuuuuuujuu,uuuuuuD3v3u3u,3u3O6yyyyqyyyqyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyy!J{cooooooooooocooocoJJoc>>{{7{{{V{V7@{{VOqyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyb{{}}o}oo}}co}}cooccooooHtHocVzPzPP..PC'SUU5U5UY5555555Y5Y55555I555Y5Y55555KKK55KKK5555555555555Y5Y5U5KUUUUUUUEkpUa*'&<6yyqyyyyqyyybyyyyb-xvQuujuQu,,,ujuuuuuuuuuu,D,uuDv333uuuu3~bbbyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyq!HoooooooHoooooooooccHJJ>z7{{{{7{17V{{{{Vmbyyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyq7V}oo}co}ocoocoocooooocotHoczzPzPP..+T'*5U5YUY5Y55Y555555Y55555III555KKKIX5XU5K555555Y5YUU5UUU5555U5UUUEUUEUUUp0rGTY<6yyyyqqyyyqyyqyyyyyNx(vjQuuQ,WWjuju,uu,uuuuuuuuuuD3333u3u3uQ^yyyyyyyqqyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyb!7}oooooooocooooooocooJcc>}{{{{{{{V7{V@V{OAyyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyq1>H}ococ}ooococoHooooocJtJooVzPPPP..+C':UU5UY55U5Y555Y55Y555555555555555U55555U5UY5U55555Y55UU55Y5UKUE5U55UUpa5GekNqbyqyqqyyqyqqyyqqyyyy6$LQjuujQu],ujujuuuu33uuuuuuuDuv33D33uuuuNyyyqyyyyyyqyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyy!77ooocoooooooooooocoJJo>>{{7{{{{17V7V{{{-byyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyybb1{}}o}coo}cooooccoooocootHcczzzzPP..+$TaUU5555U555Y55555Y5Y5555555555U5UUU5UUU5Y5U5U55Y555YUUU55UUEUEUU5U55UpK//FhyqyyqyyyqyyqyqqyqyyyqqbQLxujjuuQjuQuu,u,uuuDDuDu]uDuD3v33u3uuuQ;bqyyybyyqyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyqMoooooocoooooooooooccHJocz}{{{{{{V{{{{{{{Oyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyb8>7cooo}oooccooooooooocoJJoo{zPPPP..PTT*5U55E5UUY5Y55Y55Y55Y5555Y5Y5Y5Y5UUUUUU55UU5Y555Y55U5UUUUUKUUUUUUUEUK[)wAyqqbyyyyyyyyyyyyyyyyqqyyyO(xuQuj,uuuuujuuuuuDuuuuuuuuuDuv333Duuuu~yyqyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyM}JooocooooocooooooccJHo>z{{{1{{{{{{{{V{{-yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy1{}}oocc}o}o}oocoocococHtHcozzPzPz.++C'aUU55UUU5U5Y55Y55U5Y55555555U555UU55555Y5Y55U5Y5555YUUUUUUUUUUUEUUU5I:n6qyyyyybyqyyyyyyybyqyyqqyy6-(x3uuujujujuujuuu,Duu,uuDuuuD333333uuuj]qyqqyyqyyyqyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyqMo}coocooooooooooooccJocc>}{7{{{1{{{{V7V{-qyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyb{Vc}ococo}ocooooocoooocotoocVVPPPPPP+T_:5U5UUUUUY5UU5Y5Y5Y5UUY5Y5YUUY5Y5UUY5Y5U55UUY55Y5U555UUYU5UUUUUUUKKesh6qyqqyqyyqyyyyyyyyyyyyqqyyyy!xx3jjuuuuuujuuuuuuuuDuu,uuDuuuv3333uu3j,6yyyyyyyyyyqyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyq-}Hoooo}oooococcoooocJH}>z7{{{{V{{{1{{{V{-yyyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyb1{}}}cocoococcooooooococJoocVzPzPP..+C':U5UU5Y55UU5YU5U5UUU5555555Y55U5Y5U555Y5UUUUU5U55YUUUUUUUU5UUUUUUEI[F<<qqyqyyyyyyyyyyyyyyyyyyqqyyyyx(vQjujujuuQuu,uu,u,uuuuuDuDu33v3D3uuuuu!yyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyy-c}oooooooooooooooocococ>>{{7{7{{{{{{{{{{Mbyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyb{Vo}o}cc}oocoococooocoooHHoczzPPPz.V+C'SU5Y5UU5Y5UU5UUUUUUUYUYUYUY5UUUU5Y5YUUUUU5UUUUY5UU5UUUUKUUUUUUEUUES;qqyyqyyyyqqyyyyyyyyyqyyyyqqyyyyj(Qjujuuu,u,uuuuuuDuuDuuuuuuDu33333u3uQ3;qyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyq-7oooooocoooooocoooccHJ>c>{{{7{{{{{{{{1V7Mbyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyb7V}occ}oo}o}cococcooooooHHoc{zzPPP+P+TT:555UUU55UUUUUUUUUUUUUUUUUUUYUUUUUUU5YUUUUUUUUUUUUUYYYY55EUUUUU5UXK6qyyybqqqqyybyyyyyyyqyyyqyyyyyyqj(QvuQujujuuuu,uDuuuuu,uuDuuuD33333uu,uuw6yyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyq-c}oocoooocoooocooocoHcc>>}{}{{7{{{{{{{{{MyyyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqA{>}}cocc}occococcccooocoHHocVzPPzP.V+_'*UKU5UUU5UUUUUEYUUUUUUUUU5U55UUUUUUU5UU5UUU5UUUUUUUYYUY55UUEUUUU5IE66qbyqyyqqqyyyyyyyyqyyyyyyqyyyyqMxxjuu,Quuuujuuuu,DDuuuDuuuuuDuv33333uu3O6yyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyybO}ooooooococoococooccHHc>z7{{{{{{{{{{{{{{MyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyA{{o}cocococococoooooooccHoo}{zVPPP.$+CT:UUUUUY5YUUUUUUEUUUUY5UUU55YUUU5Y5YUUUUUU5UUU5UUUUYYY555UUUUUUU5UaX<6bybyqyqyqqyyyyyqyyyqyyqyqyyyyqNxvQjuujuuuuuuuuuuuuD]uu,DuuuuD33333uuuuW<yyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyybB}}ooooooHcccoocoooocHoc>>{7{7{{7{{{1V{{{^ybyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyybA}}}oc}ococccococccoooocooooczzPPPPPC+C'*aUUUUU5UUUUUEUUUUU5UYUUUUUKUUaEEEEEaEEUEUUY5UUUUUYYY5EUUUUUUEKUKKX4<qyyqqyyqqyyyqyyyyyyyyybyyyqyyy6xxvuQuuju,uuuuuuuuuuuuuuuuDuuD333D3uuuuj^qyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyybO}ooooooocoooooococcccHc>>}{{77{{{{{{{{V1!yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy^{Vo}ooc}ccccoococcoccocoHoccVVzPPPP$+_':KEU5EUEUEUEUUUUUU5U5UU55UUXKaXSa*KXaKKEUKU5UUUUUYYUUKUUU5KUUUU5K/IaZyybbyyyyybyyqyyyqqyyyyyyyyyyqy^O(Qujuuuuu,uuu,uDuuuDuuuDuuuuuDv3333u3j3Nyyyyyqyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyy-}JJJJoooccooooccocooooc>>{}{{{{7{{{{{{{{^yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy!{>}ooccccooccocooccocooooooczzPPPP+$+TT:UUUUUUUUUUUUUUUU5UUUEU4[#%44g4&%n==&%%:':aEEUUUUU5KU5UKUUKUUUUUUrrIKh<yyyyqbybyyyyyyyyyyyyyyyyyyyqqOLQQuujuu3uuDuuu,uuuuu]uuuuDuuDv3333u,uQwqqyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyAO7JftJoooocccoocooccoccc>>{77{7{{{7{87V{8!bqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyb!>{ococooocccccoccccocooHoHc}VVzPPP+$+_':KUUKUEUUEUEUUUUUUUUUUE:0ZFh<666666h6<h0[r*XKpUUUKUUUUUUYYUUUUUUUKI/X4|qyyyyqyyyyyqqyqyyyyyyyyyyyqyq-Lx3jujuuuuuuuuuuuuDuuuDDuuuuuD3v333uuuu~yyyyqqyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyOJtffJocoHcHoooccocooccc>>}{}{{7{{7{8{{V1Ayyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyi>Vc}cc}ocococcocccooocJtHJo}VPPPP.@CT+_SKEUUUUUEUUUEUUUUUUsY[[!qqqqyyyqy6yqyyqq;%)::EpEUEUEUU5YYYYYUUEUKUXrIXph<66yyybybyyyqyyyyyyqyyyyqqqyAxx3Quuu,uuuuuuuuuuuuuuuuuDDuuD3v333uu3u]qyyyyyyqyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyybOftfJoooccccooJoocococc>c>7{77{{7{{{1{{{8byqbyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyb->{ooccoco}ccccoooooooccoHoH7VVzPzPCCT+':KEUKUEUUEUUUUUUUUUpp*Z6yyyyyybybyybybyq6|)'*aEkUsUUUUYYYYYYUUKUUUXXGapnh66yyqyyyyyyyyyqyyyyyqyyyqyy6Wx3jjuuuuuuuuuuuuuuDuuuuuuuuuDD33333uuuuAyyyqyyqyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyybmftftJHoocooooHccocccocc>>{7}{}{{77{8{{V8byyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy->7occccccoooocoHJJHJHocJtJH}zPPPP.@Q_T_:KUUE5UUUUUEUUUUUUUk:0<qqyyyqyyqyyyyqyqAy6j)#:ksEUpUU55ZYYYYYYUpKUKUrGI[Z^6qyyyyyqqyybqyyyyyqyyyyqqyyj(3jujuuuuDuuuDuuuuuuuDuuuuDD3Dv333uuuuu!byyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyy&tftRfJoooccooooccococc}>>{{{7{7{{711{{{8byyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyybB>{ccc}o}ccooocHJHoHHJJtttoHJVVPzPP@#T+':KEUUUEUEUUUUEUUUEUk:F<yqqyyyqyyyyyqqqyybq6'%*aaKEU5Y5YZYYYYYYYUX55pEII0[hqyybyqyqqyyyyyyyyyyqyqyyqyq&xvQuuuuuuuuuuuuuuuDuuuuDuuuuuD33333uuu3Myyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyblffftfJoooocoocoocccoJcccV}7{7}{7{{{7{{{1yyqyyyyyyyyyyyyyyyyyyyyyyyyqyqyyyyyyyy69V7cccco}co}oJffJHJJJJJJJHof}PPPPPPT$T_'SKUXUUUUUUsUUUEUUUEEr!yyyyyyyyyyyyyyyyyyqyy;#)%::aUUUUYYYYYYYZZYYYUYUUIXE[Fyybyqqyybyyyyyyyyyyyyyyyqq!xvQuju]u,DuDuuDuuDuuDuuuuDuDuD3v3vuu3uuwqyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyAmflRftJJoHJooccoocoocJoc>}{{7{7777{{7V7V1yyyyyyyyyyyyyyyyyyyyyyyyyyyyyqyyyyyyyyb9>{occ}c}ccooJJfJJffffJtJJHfJPVzPPP$#TT':aUUUKUUUEUUUUUUEUUEr!yyyyyyyyyyyyyyyyyqybq6=T%*[KpUUYYYZYZZYYZZYZUYYEUKKpkbyyyqqyyyyyyyyyqyyyyyyyqqqAxvQuuuuuuuuuuuuuuuuDuuuuDuuuuDD3333u3uuO6qyyyqyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyAd8tfffHJJtJJccoooooooHJoc}}}{}7}{V7{{{{{dyyybyyyyyyyyyyyyyyyyyyyyyyyyqyyyyyyyyyb1>7cccccoc}cHJtttfftJtJfJJHf}VPPPPP#$T_'SKEUUUEUUUUEUUEUUUpU/<6yyyyyyyyyyyyyyyyyyyq66%#:#ppYYYZYZZYYZYZZYZYZYUZpXkph<yyyyyyyyyyyyyyyyqyyyyyyy6$xeuu3,uuuuDuuuuDuuuuuDuuuDDuuuv333Duu33Aqyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyybmf8tfftttttJHcocccccoJtJc{{{{}7{}{{{{{{{lyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyybV}}cccc}}cocoHHtJftftfHHJJH7{PVPPPP$#T_T:aUUUUUUEUUUKYYUEUUE*<yyyyyyyyyyyyyyyyyyyqqqq;#'::pYYYZYZYZYZYYZZZYZZZZUXpY4<yyyqqyqyyyyyyyyyyyyqyyqqyjxvu,Du,,DuuDuuuuuDDuuuuDuuuDuD3vD33uu]Q^yyqyqyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyybdfltftftttttJoooccooJJHJc}}{7{7}77{7{{1VlqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyAV>7coccccco}c}JJtftttJJHJJHH7PPVPP$'$'_':KEUUaUUUsUUUUEUUEUU/^yyyyyyyyyyyyyyyyyqyqqyb6=#4:4kZYZZZYZZZYZZYZYZYYZUaakpZ66yyyyqyyyyyyyyyyqyyyyyqqO(Qujuuu3uuu3DuuuuDuDuuuuDuDuuD3v333uuu3;qyyyyyqyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyy!9fffftttftfttJocccocJJoJ>}{{}}7{7{}{{18@lyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqiV}occccco}}cHJHftttftfffHHH87PPPP.V)##T'SaUUUUUEUUUUUEUUUUEKSAqyyyyyyyyyyyyyyyyby6yyyqq'):[[kZYYZZZYYZYZYZZYZYZpU[aUa^qyqyyqqyyyyyyyyyyyyybyyqMxxj3uu,DuuDD3DDuuuuuuDuDDuuuDDD3333uuuuwyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyy!lfRffftttttttJJHJoHoHJJJc}{}77}{{{{17188myyqqyyyyyyyyyyyyyyyyyyqyyyyyyyyyyyyyyyBV}7ccccococ}HJJftfffftttoHJ87PzPz+@)))_T*KEKUUU5UEUUUUUEUUUpr^qyyyyyyyyyyyyyyyyqyyqyqyyM##440YZYZZZZYZYZZYZYZYYapapEpn<ybqyyyyyyyyyyyyybyyqyyq^xL3j,,uuuuuDuuuuDuuDuuuDuDDD3Duv333uuu3Wqqqqyqyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyy!9f8RfRtttfttttJJoJHJJJHo>{77{7}77{787881mybyyqyyyyyyyyyyyyyyyyyyyyyqyyyyyyyyyyqlVo}coccccoJJfJJJJJJtffJHHHJJ{PPzPP$##'_':KUU5EUUUUUUUEUUUEUKI^qyyyyyyyyyyyyyyyyybyybyyy6='%:kkYZYZYZZYZYZYZYYZZKappUY4hqbqyyyyyyyyyyyyyyyyyyyqygx3jD3uDuuuuDuuDuDuuDDuuuuuuuDDv333u,3u]byyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyy!dffffffftffttttJJJtJJJJJc}71{{7771878181OyyyyyyyyyyyyyyyyyyyyyyqqyyyyyyyyyyyyqylzH}oo}c}cJJfJJH7offJHJHooHf1VPPPPC_$'#'':UsUUU5UKUUE5UUEUUEKSAqyyyyyyyyyyyyyyyyyyyqyyyyqy%%%[kkZYZYZYZYZZYZYZYYpppKpUUp6ybyyqyyyyyyyyyyyyyyyyyyjxvjjueuuDuuuDuuDDuuuuDuDuDuuuD3v33uuuuu^yybyqyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyy!9tfffttRfftftttttJtJtJto>717777771788f88myqyyyyyyyyyyyyyyyyyyyyqyyyyyybyyqyyyyA7V7}co}ooJJJttfH8JJJJfJJH7Jf7>zPzP$#'#')':KEUUUEUUUUUUEUUEsUErAyyyyyyyyyyyyyyyyyqyyyyyyqq6hQ'[[00YYZZYZYYZYYZYZYaaXpppZp!qyyyqyyyyyyyyyyyyyyyyyqwxQjuu,DuuuDu3DuuuDDDuDuD3DuuDDD3333uuu3^yyyyybyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyy!8fRff8fttffttJttttJtJJJoc8J8177188888881Oyyyyyyyyyyyyyyyyyyyyyyqyyyyyyyybyyyyyb{{}}}H}JH7JtfttffJJfJ8J7HHfJ@VPPPz#$%))'':XYUUUU5UEKUUUUUUUEE/Aqyyyyyyyyyyyyyyyyqyybyyyyyy6=)4%4kZZYZZYZYZYZYYYYZUppppEU4hqqqqybyyyyyyyyyyyyyyyy!(ee3DuuuuuuuuDuuu3Duu3DuuDDuuDDvv33]uu3w6yyqqyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyi@lffffffRffttftttttJJHHJ>1J878J78ff88d81Bqyyyyyyyyyyyyyyyyyyyyyyqyyyyyyyyqyyqq!>{o}7HoHooHHftJttfJHJHH}oHff{zzPPz=_##')':KsUUUEU5UUUUsUEUUUErAqyyyyyyyyyyyyyyyyqbyyyyybqyqy['4[kYZYZZYZYZYZYZYZZEUEpppE[FqyqyyyyyyyyyyyyyyyyyyyqxveDjuuuDuuuuuuuDD3DDDuuDuDuuuDv333uuu3w6yyqyqqyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyi@tff7J8tffftftttfttJJHJJo8878f718881888@Bbqyybyyyyyyyyyyyyyyyyyqqyyyyyyyqqybyb->7f}HH7ocoooJftttttJH}c}coJJ@zPPzV4###'T'SKEUUU5UEUUUYUUUEUUsIbyyyyyyyyyyyyyyyyyyyyyyyyyyyqqhQ%[[k0ZZZZZYZYZYZYZYZZZUZUUpX66yqqyyyyyyyyyyyyyyyyyq$xQuuu3,uuDuDuDu3DuuuDDDuuDDuuD3333uuuujAyyyqyqyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyy!@RffJfffRfftt7ttttJtJJtfo1f7177778d88181iyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyqyyyyyAdVHfHfHfHoHo}7JfftfJHH}}}}o77VzzPP1|#'##'':XEKaUU5UUUUYEUYYkUpSAyyyyyyyyyyyyyyyyyyyyqyyyyyyqq<n)g:kkZYZYZYZYZYZZYZYZZEUZpaX;66yyyyyyyyyyyyyyyyqqy6OxQ3ju,uuDuu3uDuuDDDuDDuDDuuuDDDvv3uuuuQ<qyyqyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyi1fff8fJfftfRftfftttJtttJ}18{11}18788811@iyqyyyyyyyyyyyyyyyyyyyyyyyyqyyyyqyqbyb$>JfJJH7JooHo}HHJfHo7JHooooJ7zVPPPd|T$)')':sE5UUUUUUUUYUYYEEEES^yyyyyyyyyyyyyyyyyyyqyyyyybyqyqy%%[[4nYZZZUYYZYZYZYYZYYUEKaaaFyyqyyyyyqyyqyyyyyyyyqwLQujujuuuDDuDuD3D3D3D3DDuDuuuDDv33uuuuuNqyqyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyqB@RffHfJffdfttftfftJJJtJf}1f8718188881181iyyyyyyyyyyyyyyyyyyyyyyybyyyyyyqyqybq!P>HftJJJ}ooHoJ}}o}7ooJ}}oJtf7zzzPPih)'%)'':UUUUUEUUUU5YYYZUEEEXbyyyyyyyyyyyyyyyyyyyqyyyybyqyqqqhe*[p0kZYYYZYZYZYZYZYZZZUKaa:nybyqyyyyyyyyyyyyyyqyyMvxu3,ujuuuu3uuDuuDDuuDuuDuuuuDDD333u,uewqyqyqyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyBdfff887fftfffJfttJtJRttJJJf11871811718d1BAqyyyqyyyyyyyyyyyyyyyq6qyyby6qyybyqy2z}{fJf}}7o}}J7JJococ}co}cffH7PPPzCqh$')')G:KUEUUUUEUUYYYYUUEUs:6qyyyyyyyyyyyyyyyyyyyyyyyyyyqyqq6;%*[kk0YZZZZYZYZYZYYUYZYaXUa:66yyyyyyyyyyyyyyyyyyyyQQejujuuuuuuuuuuu3DDDD3DDuDuuDDuv33D3uu~qyyybyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyymdl8ttfffftRftfftftJtJtt7o1fJf8118811111@ibybqyyyyyyyyyyyyyyyyyy6qyyyyq6qyqbybdz}HH7HHo}}}ooJfJJc}cccc}oJJHoPPzPmAh$#'#''aKU5UaUEUUUYUUUEKEYp:6qyyyyyyyyyyyyyyyyyyyyyyyyqqqqqq66%#:[k0ZZYZZYZZYZYYUYYZYUKUsa|6yyyyyyyyyyyyyyyyyyyqQxQ3uujuuDuDD3DuDD3uuDuDDuuDuDDD33uDuuu]qyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyymdffffffffffffffffftttJtJ}8f1f18JH118188@iyqq6yyqqyqyyybyyyyyyqqyybqyyqyyyyyqA{V}}}}}oooHoooHJJJo}c}cc}}J7J>PPPPMqh$')':S:aKUUUUUUEUsYUEUEUEsaqqyyyyyyyyyyyyyyyyyyyyyyqyyyqqq6q6F%'g[YYYZYYZZZZZYppYYYYYUUKK[F66yyqyyyyyyyyyyyyyyy&xeu,jj,uuDuuuuDuDDDuuDuD3DuuuDDvv3Duu3,^qyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyldllRfffff7JfftttJtJttftJo8181811f1111fd1!qq66yyqqyyyyyyyqyyyqqyyyyyqyyyyyyqyOV7}o}H}}}}o7ooHJHHH}c}cc>}JH1>zP.1qbh$##')SaKUUUEYUYYUYYUUEUUUa:qqyyyyyyyyyyyyyyyyyyyqyyyqqq6666<<h&#4*&kZZYZYZYZZZYZYZYYYYYUK[Z<6qyyyyyyyyyyyyyyybb;xejuuuuuuuDuuuD3uuD3D3uuDuDuuDD333uuuu3!yyqyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyldf8ff8fffJfffffftfftJtt}}17781111f1ffd1$bqyqbyyyyyyyyqyyyyyyqbyyyyyyqyyyyyyb1}Jc}coccc}ooo}oooooc}cccccJH1zPz.-qqh###':*aaUUUYYYYYUYUUUUsYE::qyyyyyyyyyyyyyyyyyyyyyyyqqqq6b<A^;;|g#[[ppYZYZZZZZZZZZYYYUZYUKKK<6yyyyyyyyyyyyyyyyyy<xQj3juuuuuuuuDuDuuDuDDuDuuuDuD]uv3uuuu3;qyqyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyldflfRfffffffffRffttttft}}f88J88811871111!yyyyyqyyyyyyyqyyyyyyqyyqyqqqqyqyyyiV77o}ccc}cccooH}}o}}c>c>c}JJ7VVzz$Ayqh$'#'#*:KEUXUYYYYYYZsUEEUUpkqyyyyyyyyyyyyyyyyyyqqyqqqq666<<<NM;=|%)[[pYZYZZZZZZYZZYU5UZUKUpS|6yyyyyyyyyyyyyyyyyb<$xjjjuu,DuDuuuuuDD3DD3DDuuDuuuDD33uuuuu&qyyqyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyldfflff88fftfffffftftJJt7HJff18881118818@iyyqqyybyyyyyyyyyqybyyyyyyyqqyyqqqqlVJ7}c}cc}ccoocc}o}c>ccoc}cJHHzPPz9qyy6#'#:'*:KUUUUUYYUYYYUUUsEEpkqyqyyyyyyyyyyyyyyyyyqqqq666b<!^M;M--n=%#[00ZZZYZYYZYZYUKKUUEU555&<yyyyyyyyyyyyyyyyyqqjxQjujuuuuDuuuuuuDuuDuuDDuDuuDD]u33uuuuw^yyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyy8dfffffffJffffffffttttfR}7f81f11878188d8@iyyqqyyyyyqyyyqyyyyyyyyqqqyqqyyqq6^{{7}c}c}Hoc}o}c}ccccc}ccccHHJ}PPzz!yqq<%''%:SaKEUYYU5YYYUEspUUUE:kyqyyyyyyyyyyyyyyyqqqqqq6666<^<!<N;;Ow=&%)[kkYZZYZZZZYkKU5EYp5X55%hyyyyyyyyyyyyyyyyyyywxv,W,juuuDuDuD3Du3DDDuD3uDDuu]Duvuu,,uj<yyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyldfftfffffffffftttJttJtRJo8Jf7ff118818RRllbbybqqyy6yyyyyyyyyyyqqyyyqybyyybbm>}}c>c}HJH}c}cc}cc}cc}cc>oJH8}PzPdyqqy6#%)'#:aKUEYUYKEUYUUEUkUYU:kyyyyyyyyyyyyyyqyyyqqqqqq6A6<^<M!MM;-OO==%)[4YZYZYYYZYEKKUUEYX5UX[Fyyyqyyyyyyyyyyyyyy6!xxWW,jujuD3DuDDuuDuuDuDDuuDuuD]D33]uu]Q^qyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyd8flfR8fffffffffftftttJRHo{{{{{{f181Rl22i2mbbbqqyyybybqbyyyqyyyqyybyqybbyyiV}Jo}o}}HJH}cc>ccc>c}cccccHHH{>zVPiqyqy^#%)'::aXUYYYYYUUYskYUEUkUp0yyyyyyyyyyqyyyyyyqqq666666<A^<<!h;;;||==&%#[kYZYYYYYUpUYYYEa5KKKnhqqyqyyyyyyyyyyyyyqq^QQuj,,u,,uuDuuuuuDDuuuDDDDuuD,D]33,,uDjNyyqyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyd1Jfff8flfff8ffJftJttttto}{V{{{18fll2Biiiim2i!ibbbbbbybbyqqbqbyyqqybbyybqqfz}c}}}HHJfHoo}cccccccc}c}HtHH7zVVm6yyyy6%'#S4::aE55KEEEUUYYsYYYYEpkqyqyqyqyqyyqyqqyqqqqq66qb6A<!<M;<;w;-O=Ow=#%[nkYZYYKpsYY0k4:[[%4!6q6yyyqyyyyyyyyyyyqyyQQvj3juu,uDDuuDuuuDuuDuuuuDuuDD]D3]uu]uwqyqyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyq118fRfffffffffJffJttJtttJ}>}{fdflRB2BBiii2i222OlOBOiMM!bbybyqyqyqyyybyybq-VVo}cc}}HJJ7H}c>c}cc>cccccHJHH{zVV!qqqqq6=#%'[saKEUUUKEYYUZYYZYkUE:kqqqqyqqyqyyqqqqqqq66qq<6<^6!<<<NMMM;;;O===4%[nkYYYpEKEpa::'[[4g|<<6qqqyyyyyyyyyyyyyyqqgxvju,,uueuuuuuuuDuDuuDuuuDuuD],W]]]u]]~yyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyy888fff8ftfffJfJfJJHJtJtR}}118ll2B2BiBB2tRB22B2B22222RtfftRlRm22BBiiiB2m21V>occ}o7HJ7Jooc}c}c}ccc}c>cJHJ{{VVlqbqbqbb|)%#[:sKUUUYYYZYYYYYYUpEp[kyyqqqqqqqqqqqqqqq666q66b6<6<!!<M!;M;M;;;Ow|4%%0&04%%%gg&===n=;;h;^qqyqyyyyyyyyyyyyyyyyMxQjuu,u,uD,uDuuuD3DDuuDuuuuuu]]W],DuD],qyyqyyyyyyyyyyyy",
"yyyyyyyyyyyqyyqb8J8ffff8ffftfffffJJtJttfJ7flR22BBii2l1{}oB2222B2222222RRlRff11{@111V{1VV{{c7ccc}o}ooHo}}c>ccc}c}ccoJJHH}{z{!qybbbAbh$':[ssKU5XYYYZYYYYYYUsUUa0qq6qqqqqqqqqqqq6qq6q6b66666A<<^<^!NMMMM;;|&|n=[[[0%=n||||||F|h;h666qqyyyyyyyyyyyyyyqy66xQQjju,,uuDDuuDDuDuuuuuDuDuuuuu]W],u,],Ayyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyq81fffffffffffffJfffJtJRtJ7R2BBBB2RJ{}}{}f22B22222B222RRRtRttfJ77H}717{{{>}coc}c}oooJooocccc>cccc>ccJJH7VV{ObbbyAA!hM%'#[[sKKUUYYYZYZYsUsUpEEakqA66qqqqq6q6qq6q66qq6666A6!<^!<!<MMhNh;;;;;hN|||||FZ;hhhhhhhhhh<hhq6qqqyyyyyyyyyyyyyqy6xeuuDuuuuDuuDuuuDuuDDuDuDuuuu]],WD,uu]uNAyqyyyyyyyyyyyy",
"yyyyyyyyyyyyyybA8lRfff8Rf8ffffffftftt222JJ2BBB2d87>>c>>>{lR22RR2RRRtRtRtRtf8777777{{{>>>>7cc>}o}oooJooHHc}c}c>ccccHHHH{}V8AAbbAA!!MMg#':ssUEUYYYZZYY0YYUEEpE:k6AA6666qqqqqqq6qqqq6q6q66<<AA<^<M<!M!MM!hMh;Nh^<;hFFhNhhhhhhh<<<<666qqyqyyyyyyyyyyyyby<QveuQujj,DuuuuDuuuuDuDuuDDuuu,],]]]u,]]Nqyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyqA8f8f8ffffffffJfJffftt2iBRfR22J}>}>c>>>>>fR8fRRRRRRRRRtRRtff777{}{{}V}{o}ooccccoo}ooo77Hoccc}cc>c}HJJJH{VV!qAbAA!A!M;=##[akEEUYZZZZZZYsapUEEs%n6<^666qqqqq6q6q6qqb6q666A6!<^h^<<!N<<M<^h<<6<h6h^<h<<h<<<<<<<6666666qqqqyyyyyyqyyqqyqyyOxjuuuuu,DuDuuuuDuuuuDuuuDuDDD,]],]DDWW&bqyyyyyyyyyyyyy",
"yyyyyyyyqqyyyyq!88ffffff8fffftffffffR222Rfff}>}o>>c>}{}{l22RffRRR2RRRRRtf87}{{}7{V{7>}HJooc}}c}ccoooHHHHHcc>cc}coHJoHcVzBAbbAA!AiM-;Og'%:aUEYYZZZZYUEEsUUUsE[0<6666q66666q6qq6q6q6<66A<66A^A<!<<<^<<<^<Ah<<<6<<<<<<<h<h6h<qh<6<6qq6qyyqyqyyyyyqyqyyyywxQ3u],uuu,uDDuuuDuuuuuuuuDuuuu],]]u,~WW6qyyyyyyyyyyyyy",
"yyyyyyyyyqyyyyy!8R8f8fffffffJffJftfttRR2RRfJoH}>o}}}}}}>tR22RRRRRRRRRtf87}}{7}{78fH{cJf}o}cccc}cooo7HooJfoccc>ccHHJH7}Vm6bAbA!b!!MM-nm'#aaUYYYYZYYYYYYUEEUps[0<hb66666q666q66qq666q66A66A<6A6<<!<<<h<66<<666666666666666666q6666qqqqqqyqyyqyyyyyqqyyq^vQj,,,u,uuuuuuDuuuDuuuDDuDDDuD]],]u,~~g<yqyyyyyyyyyyyy",
"yyyyyyyyyyyyqyyM88ffffJfffJffftfJftftttRtRttJJJHJJJJoo}}>}}HfttRRRRRRRffH8J1Jf87}{J8J8Joc}}oo}oJJoHJHooHJHcccccHHHoo{}8!AAAA!!!!MMMMO=#':aUYYZYYZYZYZYYUUUEY[Y<<<66q66qqq6q66q66666q666b<b666^66h<66<66666h6<6h66h6666666<6666q6qqqqyyyyyyyyyyyyyyqqqbQxuuDuD,uuDuDuDuDuuDuDuDuuuuuu]]],]]~~W^yyyyyyyyyyyyyy",
"yyyyyyyyqqyyyyyMfRlf8fffff8fffJftJffftttttttttJtttftfHH}>c>c>c>cc}}H7JHJ7J7>}}c>7JfHHJJ}ccoHoHJJfHJfJoooJJoc}coJHHHH{@!bbAb!!!!!MMM-|=%[:sEYYYZYZZZU0s0ZZZn0gFA<!666q6q6q66q6qq66q666666666666666666<6666666666<666<6666666qqqqqqqqyyqyyyyyyyyyyqqyqyqQQeu,D,,uuDDuDuDDuuuuuuDuuuuuuD]]D,W~~jwqyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyy-1llltRlRtRtffftftJtJJttttRttttttttttJJcHcoHooo>c>>>>c>>>>c>}>}7}7fHJJfHo}ccooHJJJHfJJoHHoJo}cHoJHHH{{BbAbbb!!M!!MMMM-|4%asEYZYZYZZZZZYZY0Yk:nh<<66q66q6q6qqqq666666q66666666666q6666<666<6666<6666q6q66666q6qqqqqqyqyyqyyyyyyyyyyyqyqq&x3j~],DDuuuuDuuuDuuuDuuDuD]uu,D],Ww~~Wwyyyyyyyyyyyyyy",
"yyyyyyyyyqyyyyy-8RRllRRRRRRRRtRttttffftftRtttftJttJJJHooooocJoHHHoJooHooooHoJooooHJJHooJo}c}oJHJHHJJHoJJoHococHHoH7VMb!Aib<!b!Mii!MB-|=%snZZZYZZZZkk4044[4g=AA^b66666q6q666666qq66q6q66666666666666666<6q6<66666qqqqqqqqqqqqqqqqqqqyyqyyyyyyyyyyqyqyqqNQjj,,u]uuDuDuuuDuDDuuDDuDuDuuD]~ww~~~~~qyyyyyyyyyyyyy",
"yyyyyyyyqyyyqyq-1fRRtRRfRRtRRRRRRRRtRRtRttttttJJJJJJHHooooooocooooooooHoooooooHooHHHoHHoJoooJJoHJHHJJJtJoHocoHHHHo{BAAAbb!<A!M!!M;MMMO=%#sskZYZsUaa:[404n||h^!bb66qqq66qq6q6q6q66666qqqq6q6q6666666666666qq66666q6qq6qq6qqqqqqqqqyyyyyyyybyyyyyyyqqyqq<xjjuuu,uuuuuDDuuDuuDuDDDDuu]]]~~www~~~]ybyyyyyyyyyyyy",
"yyyyyyyyyyyyyyy-1lRlRRRRRRRfRRRtfRRRRtRRtRtttttfJJJtJtHHoooooJHoooccooooooooooccooHooHHoJoJJJJJHHHHJHJtHHttHHHHHH{Obb6bAAAiA!h!!MMi-M;|O%%4=444=====O|h|;hhh<<<666q66qq66666q66q6666q666qqqqqqqq6qq66qqqq6q6qqqqqqqqqqqqqqqqqqqqqyyyyyyyyyyyyyyyyyyyqq<QeW,]uD,uuuDuDuuuuuuuuuuDu]]W~~wnww~~~Wyyyyyyyyyyyyyy",
"yyyyyyyyqyyqyyb-7lRtlRRltRRRRRRRlRRRRRtRRRRRRtRtJtJttJHoooccoJJJcocccccococoHocooooHJJJHHoJJJJHHJJJJHtJttJJtHoHH{Ri!b6AAAA!i!Ai!!MMMMM||n=[4=nnn|;h|hhihhhh6h<h66<6qq6666qqqqq66666666qq6q66qq66qq6q6qqqqqqq6qqqqqqqqqqqqqqqqqqqyyyyyyyyyyyyyyyyyqqqqq6mxW~~w~]]uuuuuuuDuDuuuuuuD]]]~nwnwww~Dwyyyyyyyyyyyyyy",
"yyyyyyyyqyyyyyb-8RdlRlRRRdRtRRtRttRtRtRRRRRRRtttttttRttJoccJJtJJcoccoccooooHHHoHHHJttJJHHoHtJJJJJttJttJtJttttJH}miqbAAAAAAb!!!!!M!!MMihM||=|nhh|hhhhh<h<hh6<66q66q666q6qq66qq<qq6qq6qqqq6qqqqqqq6qqq6qqqq6qq6q6qqqqqqqqqqqqqqqqqyyyyyyyyyyyyyyyyyyyy6y6wxW~~]~~]DuuuuuuDuDuuuuDuuu]W~~wnww~wjNqyyyyyyyyyyyyy",
"yyyyyyyyyyyyqybO1RRRRRRRRRRRRRRRRRRRRRRttRttttttttttttttJHHHtJtJcocccoJHHoHHHHHHHJJHHJHHHHHtJftJJtJJtJtJtRtttfHR!b!bb!A!!biAi<<!!!!!hMMMMMhMMhMhhh<<hh<h<h<h<6666qqqq6q6qqqqqqqq66q66qqqqq6q6q6qq6qqq6q6qqqqqqqqqqqqqqqqqqqqqqyyyyyyyyyyyyyyyyyyyqyyqqq!QW]~~~~~~]]uDDDDuuDuuuuuuu]D~~~nwww~jNqyyyyyyyyyyyyy",
"yyyyyyyyyqyyyyb-1ldRflRRdRlRRRRRRttRRRRttRRRRRtRRRRtRtttttJoHJJHoJoooJJttttfJJfJHJJJHHJJfJJJftJJJttJJJttRRRRl{diqb!AbAbAAAA!b!<!<b!!h!!bhihMhh<<hh<<<h6h<hq<6h6hq6qbq666666666666666666qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqyyyyyyyyyyyyyyyyyyyyyyyqqAx%~]~~~~]~~DDuDuuuuuDuuuuu,,]~~ww~~]Qqyyyyyyyyyyyyyy",
"yyyyyyyyyyyyqybO7lRlRRRRRRRRRRRRRRRRRtRRRRRtRRRRRRRRRttttJHHJooooHooHttttRRRftRttJtJJfJfJfJtJJtttJtJfttRtRtt11ibbbAAAA!AAA!bi!!A<!<!!!<!<<<66h6hhh<h6hh<h6h6q66qhqh6666666666qq66666q66qqq6qqqqq6qq66q6qqqqqqqqqbqqqqqqqqqqqyyyyyyyyyyyyyyyyyyyyyyyqyqqqOxD~~]~~~]],,,DDDDDuuuuuuuuDD~~w~~wWw6yyyyyyyyyyyyyy",
"yyyyyyqyyqyybybO1llRRdRlRRRdRRRRRRRRRRRRRRRRRRRRRRRRRRRRttJHocoJoJooJtRRtR2RRRRRtRtRRRttfttJffJJtJttJttRRtf79!AbAAA!Ab!b!bAAAAA!!<!!A<Ahb<hbhh6<h6<<h6<<h66hq<66qqq666666666q66666qq6qq6qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqyyyyyyyyyyyyyyyyyyyyyyyyyyqqNQe~0~~~~~~~]]~DDD]Duuu~DDuuDDD]~~~]w6yyyyyyyyyyyyyy",
"qyyyyyyyyyyyybqm8lRlRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR2RRRtttJoococoooHttRRRRRRRRRtRRRRRRRRRRRtttttJftRRRttt7tAbbq!b!AAAAAb<!AA!A!AhA<Abbbqbh6bh6h6h6h6h6h6h66qhqh6666666666666666666qqq6qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqyyyyyyyyyyyyyyyyyyyyyybyyyyyyq6N33]~~~~~~~~~],DD]uuu]]]D,,],]D]]W,;qyyyyyyyyyyyyyy",
"yyyyyyyyyyyyqbqO1lllRRRdRRRltlRRRRRRRR2RRRRRRRRRRRRtRRRRRRRttJHHoHoHHJtRRRRRRRRRtRRRRRRRRRRtRRRRtRtRRRRRf7d!bbqbAbAb!bAbAAA<A<AAbAAh6b6qq666666h6<6<q<qhbq6bqqqqq6666666q6666666q6q66qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqqNj$geQWDW]~]W,ujuD3DD~]DuuDD,~]]wQ^byyyyyyyyyyyyyy",
"yyyyyyyqqyybbbAO8RlRRlRlRRRtl2RRRRRRRRRRRR2RRRRtRRRRRRRRRtRtttJHoJJJJJttRRRRRR2RRRRRRRRRRRRRRRRR2RRRRttf8dA!qAbqAbbAbbbAbbb!Abhbb<bb6<66q6666q<6bhq<h6h66bhbhq66666666666qq6q6666q66q6qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqyyqqqqN-~%jeeQ3vQ3ju33u3uD]],juuu]]w~&Wqyybyyyyyyyyyyyy",
"yyyyyyyyyyybbbAO{lllllR2RRRRRRR2RlRRRRRRRRRRRRRRlRRRRRRRtRRRttJoJHJJJHJttRRRRRRRRRRRRRRRR2RRRRRRtRRtRtd{mbbbbAbbAbbAb!bAbbhbb6bbhb6q66q6hqqhb6<6hbhbbbqb<qqqqq666666666qq6q666q6qqqq6qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqq6<N;wwO&O=Oj%jQQQ$QQQuujQuuu,~]W3N66qyyyyyyyyyyyyy",
"yyyyyqyyqbqqbbb!d{lRlRlRRlRRRtRRRRRRRRRtRRRRRRRRRRRRRRttttRtttJoHooHHHJJt2RRRRRRRRRRRRRRRRRRRRRR2RRtRJ8BbAqbAAAAbAAbAAAb6bbbqbqqbhbqhqq6qqb6b66qb6bh6h66bh66666666q66qq66q6qq666q66qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqqq6<^NM;;OOOOOOOOWww&QQ3v33vvv3Q3w<q6yyyyyyyyyyyyyy",
"yyyyyyyqqybqAAbbB9$$@dddddldllmflllRlRRlRRlRl2RRR2RRRRtftttttfJJf8HHooJJtRRR2RR2R2RRRRRRRRRRRRRtttlt@diAA!A!A!bAAA!bAAbAbbAbhqbhqbqqqq6qqqhqhq6hb66b6bqb6qq66qq6q66q6q666qq6q666qq6qqqqqqqqqqqqqqqqqqqqqqqqqqqqqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqqq6<^NNN;;w-;OwO;wO;-;M;--OOO&-66qqyAqyyyyyyyyyyyy",
"yyyyyqbyqbyqbbbAA!imd9@@@1dd81dlRRllllRlllRRRRmRRRRRttfHfttfttRfRtttJ}oJtRRRRRRRR2R2R2RRR2tRRRRRRt17-i!A!A!b!Ab!bbbb!Abbbbqb6bqqqh6qhqbq6qqqq6bbbbqhqhbb6666666q66q6q6qqqqqq6qq66qqqqqqqqqqqqqqqqqqqqqqqqqqqqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqqqq66<<^M!M;;;;w-O-O-;w;;MNN^<<qqyqyyyqyyyyyyyyyyyy",
"yyyyyyyyybqqqbbA^A!bAMiMOd99m9$@@@8ddddlllllllRRRfffflf8fffRRRRRRRRRt7}JttR2RRRRRRRRRRRRRRRRRtff{@mii!!!!!!AAi<bAAAAbAAA<6666b66q666qq66q6qhqhqq<hqqqq66666qq6qq6q6q6qq6qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqy6qqq6<6<^NNMw!;;;;;;;;wM!!!N!AA^qqyqbbyyyyyyyyyyyy",
"yyyyyqybybbqbbAAAAA!!!Ni---OOmmmldd1111181f8fflRlf8flRRtf8ffRRRRRRRRRJJ7JttRR22RR2RR2RRRRRRlRff8mmBi!;i!!!AA!AhAb!bbb!Abbbb6666b666666666qqqq666bbb6666666q6qqqqqq66qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqyyyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqqqq66q6<<^<^NN!wN;MwMMMMNM!!^AAAqyqybyyyyyyyyyyyyy",
"yyyyyyyyqyybbAAAAA^!^!!MM---OOwOOWm&OmWm9999$$@1V@@dd8dff87fRRlRRlRRtfffftRRRRRRl2RRR2RRlRd1@@mOiOMiMM;!!!iAibA!bbAAAAA<bbb6b666b6666666666666666666666q6qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqqqqq6q66<6<^^^NMNNNNM!MNN^!N^<6bqqyyyyyyyyyyyyyyy",
"yqyyyybqybbqbbbAA^^^!!!MMi-O-OmOwmgOmgmOgOmOdmmdld1@111{1{{71ff8flRRfftRftftRRRRRRRdRf8f88@lmOBOBMMMM!M!i!!A!!b!bbbAbbbb66b666bb6666b66666666666666666q6qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqyyyyyyyyyyyqqqqq6<6<6<<^<^!^^!N!NM<^^<^A<q6qqyyyyyyyyyyyyyy",
"byqyyyqqyqyyqqA^AA!^N!MMM----w-OwOOO&OOmOm&O&OWO&OgOOgm99$@$$@@$@@1@111111dddddd1dd1@@99dOOOOO--M-MMi;!i;!!b!AA!b!AbbAbbbb6bb66666666666666666q666q6q6qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqyqqqq666666<<<^<^<<^^<!!^^A^Abbqybqyyyyyyyyyyyyy",
"yyyyybybybbbbbb6AAA!!!MMMM-M---O-w-OOOwO&mOmOmmO&mOmOmWmOOmOmmmdld819111{111111111dllmmmOO-OBM---MMMM!!h!!!!b!b!AAh!Abhbbhb6b66b6b66666666666q6q6666qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqqyq6q666<66<<6<^6^<^^AAAAbbbqqyyybyyyyyyyyyyyy",
"yyyyyqyyqqqbbybAAAA!!!!MMMMMM---------O--wOwOwOOmwmOOOOOmOOOOOOOm&OOmO&OOOOO=mOOOOOOOOOO-OOO--i-Bi;!MM!!!bA!AAAAAAAbbb6bbb66666666666666q6qqqqq66qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqqyqqqq66<q<6<<<<666<^6^AAbqqqqyyyyyyyyyyyyyyyy",
"yyyyyqbyqyyqqbbbAAAAA!!!!!MMMMMMMM--w----O--OOO---O---wO-WOmgmOOOO&OOmOm&mOmOOOOOmOmO-OO-M-M---;-BMMi!!!!i!A!!AhA!bbbbbb6bb6666666666666666q66qqq6q6qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqyqqqqq6666<q6<6<66666b6q6qqqqqqyyyyyyyyyyyyyy",
"yyybyybyybybybqbAAAAA^!!!!!!M!M!MMiMM-MMM-M--M------O-O----O-OOOOOOOOOOOO&OOwmwmOwOO-O----B-MMMMMM!M;!iA!A!!bAAbAbbAhbbhb6b6666666666666q66qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqqyyyqyyyqyqqqqqq6666<<66666<q66qqq6yyyyyyyyyyyyyyyy",
"yyyybyyybyyqbqbbbbbbAA!^!!!!!!!M!!M!MMMiMMiMMM-M-Mw----wO--w--w-O-OOwOO-OOOOO----O-----i--M-MMiM!MM!i!!!AAAAb!b!Ab!A6bbb6b66q6666666qq6q66q6qqqq6qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqyyyqyyyyqyyyyyq6q6<66666666bq666qqqqqqqyyyyyyyyyyyyyy",
"yyqyyybyybyybqbybAbAAbAAAA!A!!!!!!!!!!!M!MMMM!MMMMMMMM--M-w---------------w----------M--MMM!M!M!!!!!!b!!AAAAAAAbbbbbbbb6b666666q66qqqqqq6qq6q6qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqqqq6qq66q6q6qqqqqyyyyyyyyyyyyyyyyyyy",
"byyyyqqyyqyqybqqbbbbAbAAAAAAAAAA!!!!!!!!!!!!!!M!!M!MMM!MMM!MMM-MM-M-M-M-M-----M----Mi-MMM!MMiM!i!!!!!!b!Ab!AA<bbb66b<bb666666qq66q6q6q6qqqqqqq6qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqyqqqqqqqqqqqqqq6qqyqyqyyyyyyyyyyyyyyyy",
"yyyyyyyyyyybqbbyqqqbAbbbAb^AAAAAA^Ab^A!!^!!!!!!!!!!!!!!M!M!M!MMMMM!MMMMMMM-!MM-MM!MMM!M!iM!MM!!!!!!bbAA!AbbbbbAbbbb66bq6q666q666q6qqqqqqqqq6qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqqyqqqqqqqqqqqqqqqyyyyyyyyyyyyyyyyyyy",
"yyqyybyybyyyyyybbybbqbqbAbbbbAAbbAAAAAAAA!A^A^A!!^!!!!!!!!!!!!!!!M!MM!MM!M!MM!M!MMM!M!!!!!!A!!A!!!AAhAAhAAAbbbb6bbb666q666qq6qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqyqqqqqqqqqqqqqqqqyyqyyyyyyyyyyyyyyyyy",
"yyybyyyyybybyqyqybybybqbbbybbbbbAqAbbbAbbAAAAAAAAAAAA!^A!!!!!!!!!!!!!!!!!!!!!M!!!!!!!!!!!A!!AA!bbAb!b!bbbAbbb6666q6qb6bqqq6qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqqyqqyqqqqqyqyyyyyyyyyyyyyyyyyyyy",
"byyyybyyyyyyyyyyyyyqyqbqybybqbqbbbbbbbbbbAbAAbAAAbAAAAAAAAb!^A!!A!!!!!!!!!!!!!!!!!!!!!<!A!AAAAAAAAbb6b6Ab6bqq66bb6b6qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqyqqyyyqyyyyqqyyyyyyyyyyyyyyyyyyyyy",
"yyyyqyqyqyyqybbyybybyyyyqyqbqbqbbybqbbbbbqbAbbbbAbAAAAAAAAbAAA^AAAbAb!bA!A!!AAA!!AAAA!AA!AAA!AbAAbAbbbb6qq66bq6qqq6qbqq6qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqyyyyyyqyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyqbybbyyybqyybqyqybbbbbbqbqbAbbbbAbAAAbAAAbAAbAAAbAAAAbAAAbAAAAAAbAbAAbb6bAbb6bqqbqqb6bq6qqqqbq6qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyybyyyyyybyyqyqybybqyqyqqbqbybbqbbyAbbbAiBiAbbAA!bbAAbAbbAAAbAAAqbAAAAbbbAbqbbqbqq6FhhAbqbqqqqqqqbqqqqqqqq6!qqqqqqqqqqqqqqqbqqqqqqqyyyyyyyyyyyyyyyyyyy^^^NyyyyyyyyyA!!qyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyqyqbyybyyybyybybybybqyqbbbyqyqbqqbqybbbqbBcJJcRbb!ObbbbbAqbAbAAqbqAbqbbbObbqbqbqbqbqhIKXIFqqqqqqqqqqqqq6q6qqbO6qqqqqqqqqqqqqbOqqqqyyqyyyyyyyyyyyyyyyyyyq|D3~yqyyyyyyqOM!yyyyyyyqyyyyyyyyyyybOyyyyyyyyyyyyyyyyyyyyybOyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyqyyyyyyyyqyyyyybyybbyybqbyyybqybqyicAABcBqb!bbbMA!bb!-MAbqb!-MAb!=!Abbqqqqqqb|I<qUaqq!-MAqqb!;-bqqq!-|OqqqA-|Aqqq!A!qb!qqq!!;Ayyy!-M!yyyyyyyyyyyyqwD6yA!!;!yy!O!^yq!A!yqMMMqyyyM-M6q!O^Ayq!A^yb!yq!qyy^-MAyNO!Ayq!yb!yyq!A^yyA-MAyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyqyyyyyyyybyyqyyybyyyqybyyybybbBcyqbttbAOybAOOMq^-!MObq!O!;!bMO;!qqbqqbqqqhIyqUaq<OA!OqqbO!;-qq!OA!OqqbObM-bqA=-!qbOqqAO!M-yq^Ob;Oyyyyyyyyyyyq6~Dyy^O!M-yqNO!AyAOO!yb!A-;yyM;b!AyNO!AyAOOMqbOqAOyq!-^!!y!ONAqAOqAOyqAOOMy^O^!Oyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqyyqyyyyyyyyqyyyybbyqyqyyicAyyRJyA-bqA-AybMwM!OAb-MqqyqA-bbqqqqqbqqyhIKXa<q;-!!Obq<OqAOqq-;qAOqq;-!!O<qAO6qqAOqyAOqAOqyM;yAOyyyyyyyyyyyyy~DqyAOqbOyyAOqyyAOqqyq!w--yyM-!qyyAOqyyAOqyyAOyAOyy-MyqqyAOyyyAOy<Oyy<OyyyMw!!wAyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyqyyyyyyyybyqyqyyyyyyyybyyybAicybytRq^OqbAOyby--!!Mqq-!qqqbAOqqqqqqqqyy6FINIU6q|-;!!bqbOqbOqqM!qA-qq--;!!bqAOqqqbOyy<OqAOyyM!y<OyyyyyyyyyyyyqwDyy<OyAOyy<Oyyy<OyyyM-!MMyqAw-OAyAOyyqAOyyqAOqAOyqM!yyyy<OyyqAOybOyybOyyywM;!!byyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqyqBcbyiciy!OyqAOqyqM-6qAAyM-qbAyAOqqqqbqqyyqqhI6^I0yM-qqbqqAOqAOqqM|q!OqqM-qqbqqAOqqqAOyyAOyAOqyM-yAOyyyyyyyyyyyyywDyyAOqbOyyAOyyyAOyyy-NyM-yyAyy-NybOqyyAOqyyAwq!OyyMwyqAyA-qyybw6!OyyAOyyyM-6qAqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyybyyyyyyyyyyyyyyyyyyyyyyyyyyyyqyybyyyqicJJc2bybOyqAOyyyq---Obqb---!y6--!qqyyyyyy6NIqqZIFb---OAqbOqbOqqbO--Oqq6---ObqbOyyy<Oyy<Oy<Oyy<O-OOyyyyyyyyyyyqwD3~y<OqAOyy<OyyyAOyyq!O---yyM--Oby6--!y<OyyyyOw-Oyyb--O!q6O-!yyO--Oyy<Oyyyb---Obyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyAiiiAyyyqAyyqAyyyyyb<qyybqA^qyyqAqyyyyyyqyq6Fqyyh<qq<AqqqqbqqbqqqqA6bqqqqbbqqyqbyyyqbyyqbyqbyyyb<!-qyyyyyyyyyyy<NNhyybyqAyyqbqyyyAqyyybbqAyyybAqyyy6AqyqAyyyyybq<yyyqAqyyyqAqyyqAq<yyyAyyyyyAAqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqqyyyyyyyyyyyyyyyyyyqyyyyyyqyqqqyyqqqqyqyqqqyyyyyyyyyyyyyyyyyyyyAO;O!yyyyyyyyyyqq6qqyyyqyqyyyyyyyqyyyyyyyqyyyyqyyyyyyyqyyyyyyyyyyyyyyyyyyyyyyyyyyqyyyyyyyyyyyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqyyyyyyyyyyyyyqyyyyyyyyyyyyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyAA6yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqqyyyyyyyyyyqyyyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyybyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqyyyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyybyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqyyyyyyyyyyyyyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqyyyyyyyyyyyyyyyqyyyyqyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqyyyyyyyybyyyyyyyyyyyyyyqyyqyyyyyyyyyyyyyqyyyyyyyyyyyyyyyyyyyyyqyyyyyyyyyyyyyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqyyyyyyyyyyyyyyyyyyqyyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqyyyyyyyyyyyyyyyyyyyyyqyyyyyyyyyyyyyyyqyyyyyyyyyyyyyyyyyyyyyyyyyyqyyyyyyyyyyyyyyyyyyyyyyyyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqyyyyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqqqqqyyqyqqqqyqqq666qqqqy^NNNyy66yy^N^N^N<^6yqqqbqyqqyyyy^w|NNyqbqyqbyqyyqyyyybqqybqyq^^N<qqq6qy^N^q6^N^N^N^qqqqqqqqqqyqqyyyyyyyyyyyyyyqqqqqyy^NNNqqqqqqqqq^NN^yyqq6q6qqqbqqqqqyqqyyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqbq666A666^^^<6N^NN^NNN^^6^]DDDDDN6^^<DDDDDDDDDw^66<b666666NDDDDN66666666666b66666A^6<^<6wDD~6^^6qwDDw6NDDDDDDD^<^^<^6A66666bqqqyyyyyyqq666A66q6~DDDDDw6<N66wDDDDD~6<^N^N^^^^<66666A6666qqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqq66^6^^^<6<^^N^N<NNNNNNN<<DDDwwDDDb<^NDD~ww~~DDD~6^^^^A^6qqDDDNw66A6666b66666qb666<6^A6^6q~DDN6<<;DD~<<NDDDDD]Nq<^AA^6^6666q6qqyyyyyyqq6b66^^66]DDwwDDDN6^6~DD~w]DDw<NNNN<N^<^^6^^<^6^6666qqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqbqb66666<6^^<<N<NNNN|NNNN<]DDN<<~DDN^<wDDN<<^<NDDDN6<^<66q6NDDN6qbAqbqyyyyqqbqyqqq66^^<^^<6wDD~^qwDu~66<NuD|<<66Ab66qq6qqybyqyqyyyyyyyyyqqq66AqwDDN6qwDuN<6wDD;6<NDDw<NN<NN<N^^<^^6^^6666bbqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqqqqb666^66^^<^<N<<<NNNN^6]Dw^<Aw3DN^<~u3h<NN^<w3uw6^N^^6qNwu3N;6A6NwwwN<qbqqNNNwww<6^<^N<<<]u3NNuuD^<^^w3u|^6<^N;Nwww6qbNwwww6q666yqNwwww6q666]uD6<<NuuN<^DD~<<<<w~N^NNN<<^<6^6666666qbqqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqbq6666<66<<^<<<<N<66<<^<^uuu^<^DuuANwww^|uu~<N;NNNh3D3D3u^NuuuD3u3^6^63u3Duu;^N^NNNN<|uuDD3D^^<^<~3uw<N6N3u3DuDw<DDuDDuuN^N6^Du3DuuuN<N<]uuN^ND3uN<|u3NN;;NA^^NNNN^^<6<66666qqqyyyyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyybqq666qA6A6<^^<<<<<N^^NAbN~u33|^^<u3D^!wwM^;v3~^;wNNNN;DvD||;u3u~|w33u<6;333]~~<N^NNNNN<^D33uu^^;w^NDuD3uw^N3D3D]~^D3u]N~33D<^^Duu~N~u3D^^<Nvuu~u3uwN^D33Dv33u~A^;;;NNNN^^^<6<^666666qqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyq66b6666<6^^<6^^^^N<N^NN;3v33wA^^Nv3wNMwww<|33w^wNwNN6NDv~^N]v3N^<<]33N^|33~^<^^NNNNNNN^<;333;^Nww^^3vvDwwN~33~<^^~33;<^<]33^<~v3w<^<]v3<<NNu3u3v3&NN^3333u~3v3w^ww;NNN^N<N^^^^^^^^66bqqqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqqqq6666666<6^<^<<^<N<N^^wwwu3vwN^;33~^Mw-N<~3vw^;;NNN6^3v~^;3v]^^N^wv3;<w3vNA!N;;N^h^<<6^uvLu]^!wM<N3v~NN<N~v3NN^^3vu|;;N]3v^^33uNwN;]3v^<w3v3w~u33w!;3vv~N^;v3u^;;;NNhN^N<<^<<^6<66666qqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyybqbb66<6^6<^<^<<N<^<<<<^Nvvu^^]vv;^ww;<^uv3N^wwNNN<|vv;Nwv3;^wN<WvvN<3vu<^www;NNNN^6<3vv3v3N!wM<w3vNN^qNjv3!^N;vvvvvLvvv3N|vvvvvvvvvvNN3vuNNNN3vuN|vvuN^N^uvu^NwNNNN<<N^^<<6<^b66bqbqqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyq6q66666^^<<66^^^<q6b6^N^^vvu^^jvv^!wMN<Nvvu^;wN;NN<~LvN^WvvN^MNA,vvN^vv]^;www;;NN<66uvv~jvv~^MN^~vvNNbN^vvW^N!]vv]~~W~W~~N~vv]~W~~~~W^wvLw^;N!3vuNwvv~^MNNuvu^MN;N<^N<<^^<^6^<6bq66qqqqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyybqq6qb6666A6^^^<^<^N^N^N<wvL^AN^NvLW^^3vv^<N^^A3LL;^Mww;^^qWvLA!~LL^^N^Nvvj<NLvW^-wwNwN^^6<uLvw^NvLLN^N^WvL^^^NNLv~!N^~LvN^^N^;Mw^~LvN!<^^w;;^WLv^^N^^LvjN;vL;!N^-vLW<NwNNN<<^N<^<6^666bbqb6qqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqqb6q666^^^<^<N<NNN^NNNN6~LLw^A^uLLw!^LLu!!^ANjLLW^www;NN^AvLu^^WLLw!^^jLLw^wLLM^ww-;NNN<b,LL,^<^uLLjNb^3L3!!^^wLLw!;NwLLwN!NjLLw!~LLwN!!jLL~N~LLwN!NjLLw!;LLu^N^3LLNN;;NNNNN^N<^^^^^6666666qqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqb666^^^6^^6^<^<NNNNNNN<NvLLwwvLLW^!wLLLQ3Q3LLLj^^-ww;NNA6LLW!^;LLL&w3LLW^!wLL;!Mww;NNbb3LLWA^M!^LLLNAALLW<^M!wLL;^ON;LLLWwQLLQNNNLLLWw3LLQ!^wLLL&wuLLQN^NvLLW&3LLwN;wwwN^N<N<^<<<<^6^A6b6bqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyq666A66666^<^^<NhNNNN^^wLLLLLLw^N^wLLLLLLLLvwA^ww-;NN<^NLLw^!^~LLLLLLw^^A3LL^NwM;N^N6wLLvAA;wMNWLLvA;LLO^;w^QLL^NwM^~LLLLLLu^!N!wLLLLLLWN!N!wLLLLLLW^!w^wvLLLLLw!NwwNN^N<<^<^666A666666qyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqyqyqyyqqqqqqqqyyqyqbNwW~w^A!!!N;MwwMw;!6qA!!N!^66yq6;-^!!!ANOWWw^A^!!M;;^!N^^qyyqMN;Ab^MN!!NMMwqAw;^^!MANwNA!N!Ab!OW,wNbANM!ANOWWONAAN!!N!WWW&^b!N!!A!OWWw^A!!M!^^6qqqqyyyqqyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyybqbbbAbbA!!N!^AAAAA^bA^!!MN!!AqqyybqAAN!!!AbAAbA!!!N!^!!!!Abqqqyyyqb^!!!!^!A^AAAA^A!NM!AAA!!!!AAAAAAAA!!MM!!AAAA^A!!!M!!bAAAAA^!MM!NAAAAAA!!N!!Abqyyyyyyyyyyyyyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqA^AA!!!!!M!!N!!!MM!!!!N!!NAqybyyq^A!!!N!!!!!!NN!!!!!NM!^Abbyyybbb^!N!!!!^!!!N!!!!!M!!^!M!N!A^^^!!!MM!N!^!!N!!MM!MM!^!!!!!!!!M!N!!!!!M!!M!!!!^Abyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyybbA!!!N!!!!!!!^M!M!NMN!M!AAAqqyyqqbAAN!AAN!!M!M!!!!^!^^!AAqyyyqbbAA!!!^AA^!!!!^N!!!!!N^!!!^A^bAA!!!!M!M!^^A!!!!N!NN!^^^!!!M!!NM!!^AA!!!M!M!N^bqqqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqqq^A!N!!M^^AbA!!N^!!!!!^AAbbyyyyyyqAAAAAAA^^^!!^NAAAAAAAAqbqyyyyq^AA^AAqbbA^^AAAAA^AAAAAAAA6AqqAAN!!!^AAAbAA^^!!!!^AAAqAA^!!M^A^AqA^A^!!!N!AAAqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyybqbAA^AAAAbbbbAAAAA^AA^bqqqyyyyyqbbbAbbbbAAA^^AAAbbbbbAbqyyyyyqbbbAA6bqyqbA^AAbAqbbAbqAAbAbbybbbAA^A^AAb6bbAA!A^AA^6bbbA^AAAAA^bqbbbAA^AAAbbyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqqqqbAq^qqqqyybbAAAqbbbqqyqyyyyyyyybqyqqqqbbbbbbqybqqqqybyyyyyyqqybqbyyyyybqqbq6bbqqqbqqqqqyyyybbbAbbqbqyyqqbbbbbbybyybqbqbbbbbqqyyqqbb^bbqqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyqqbqqbyyyyyyybqbqqqyqyyyyyyyyyyyyyqyyyyyqqbbqyyyyyyyyyyyyyyyyyyyyyyyyyyyyqyyqyyqqyyyyqyyyqyyyyyqqbqqyyyyyqyybbybyyyyyyyqqbyyqyyyyyqqqbyqyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy",
"yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"]
